/*
Hanzo Cloud — Unified API (V8 · Open Edition)

The single unified OpenAPI surface for ALL Hanzo services, aggregated from the per-service specs. Every route is https://api.hanzo.ai/v1/<service>/_*. Grouped by the canonical domains in capabilities.yaml (the ONE registry). Regenerated by merge.py — edit the per-service <svc>/openapi.yaml + capabilities.yaml, not this file.

API version: 8.0.0
Contact: support@hanzo.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cloud

import (
	"encoding/json"
)

// checks if the DidListTeams200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DidListTeams200Response{}

// DidListTeams200Response struct for DidListTeams200Response
type DidListTeams200Response struct {
	Teams []DidTeam `json:"teams,omitempty"`
}

// NewDidListTeams200Response instantiates a new DidListTeams200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDidListTeams200Response() *DidListTeams200Response {
	this := DidListTeams200Response{}
	return &this
}

// NewDidListTeams200ResponseWithDefaults instantiates a new DidListTeams200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDidListTeams200ResponseWithDefaults() *DidListTeams200Response {
	this := DidListTeams200Response{}
	return &this
}

// GetTeams returns the Teams field value if set, zero value otherwise.
func (o *DidListTeams200Response) GetTeams() []DidTeam {
	if o == nil || IsNil(o.Teams) {
		var ret []DidTeam
		return ret
	}
	return o.Teams
}

// GetTeamsOk returns a tuple with the Teams field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DidListTeams200Response) GetTeamsOk() ([]DidTeam, bool) {
	if o == nil || IsNil(o.Teams) {
		return nil, false
	}
	return o.Teams, true
}

// HasTeams returns a boolean if a field has been set.
func (o *DidListTeams200Response) HasTeams() bool {
	if o != nil && !IsNil(o.Teams) {
		return true
	}

	return false
}

// SetTeams gets a reference to the given []DidTeam and assigns it to the Teams field.
func (o *DidListTeams200Response) SetTeams(v []DidTeam) {
	o.Teams = v
}

func (o DidListTeams200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DidListTeams200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Teams) {
		toSerialize["teams"] = o.Teams
	}
	return toSerialize, nil
}

type NullableDidListTeams200Response struct {
	value *DidListTeams200Response
	isSet bool
}

func (v NullableDidListTeams200Response) Get() *DidListTeams200Response {
	return v.value
}

func (v *NullableDidListTeams200Response) Set(val *DidListTeams200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableDidListTeams200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableDidListTeams200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDidListTeams200Response(val *DidListTeams200Response) *NullableDidListTeams200Response {
	return &NullableDidListTeams200Response{value: val, isSet: true}
}

func (v NullableDidListTeams200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDidListTeams200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


