/*
Hanzo Cloud — Unified API (V8 · Open Edition)

The single unified OpenAPI surface for ALL Hanzo services, aggregated from the per-service specs. Every route is https://api.hanzo.ai/v1/<service>/_*. Grouped by the canonical domains in capabilities.yaml (the ONE registry). Regenerated by merge.py — edit the per-service <svc>/openapi.yaml + capabilities.yaml, not this file.

API version: 8.0.0
Contact: support@hanzo.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cloud

import (
	"encoding/json"
)

// checks if the MqListObjectStores200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MqListObjectStores200Response{}

// MqListObjectStores200Response struct for MqListObjectStores200Response
type MqListObjectStores200Response struct {
	Stores []MqObjectStoreInfo `json:"stores,omitempty"`
	Total *int32 `json:"total,omitempty"`
}

// NewMqListObjectStores200Response instantiates a new MqListObjectStores200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMqListObjectStores200Response() *MqListObjectStores200Response {
	this := MqListObjectStores200Response{}
	return &this
}

// NewMqListObjectStores200ResponseWithDefaults instantiates a new MqListObjectStores200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMqListObjectStores200ResponseWithDefaults() *MqListObjectStores200Response {
	this := MqListObjectStores200Response{}
	return &this
}

// GetStores returns the Stores field value if set, zero value otherwise.
func (o *MqListObjectStores200Response) GetStores() []MqObjectStoreInfo {
	if o == nil || IsNil(o.Stores) {
		var ret []MqObjectStoreInfo
		return ret
	}
	return o.Stores
}

// GetStoresOk returns a tuple with the Stores field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MqListObjectStores200Response) GetStoresOk() ([]MqObjectStoreInfo, bool) {
	if o == nil || IsNil(o.Stores) {
		return nil, false
	}
	return o.Stores, true
}

// HasStores returns a boolean if a field has been set.
func (o *MqListObjectStores200Response) HasStores() bool {
	if o != nil && !IsNil(o.Stores) {
		return true
	}

	return false
}

// SetStores gets a reference to the given []MqObjectStoreInfo and assigns it to the Stores field.
func (o *MqListObjectStores200Response) SetStores(v []MqObjectStoreInfo) {
	o.Stores = v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *MqListObjectStores200Response) GetTotal() int32 {
	if o == nil || IsNil(o.Total) {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MqListObjectStores200Response) GetTotalOk() (*int32, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *MqListObjectStores200Response) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *MqListObjectStores200Response) SetTotal(v int32) {
	o.Total = &v
}

func (o MqListObjectStores200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MqListObjectStores200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Stores) {
		toSerialize["stores"] = o.Stores
	}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	return toSerialize, nil
}

type NullableMqListObjectStores200Response struct {
	value *MqListObjectStores200Response
	isSet bool
}

func (v NullableMqListObjectStores200Response) Get() *MqListObjectStores200Response {
	return v.value
}

func (v *NullableMqListObjectStores200Response) Set(val *MqListObjectStores200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableMqListObjectStores200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableMqListObjectStores200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMqListObjectStores200Response(val *MqListObjectStores200Response) *NullableMqListObjectStores200Response {
	return &NullableMqListObjectStores200Response{value: val, isSet: true}
}

func (v NullableMqListObjectStores200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMqListObjectStores200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


