/*
Hanzo Cloud — Unified API (V8 · Open Edition)

The single unified OpenAPI surface for ALL Hanzo services, aggregated from the per-service specs. Every route is https://api.hanzo.ai/v1/<service>/_*. Grouped by the canonical domains in capabilities.yaml (the ONE registry). Regenerated by merge.py — edit the per-service <svc>/openapi.yaml + capabilities.yaml, not this file.

API version: 8.0.0
Contact: support@hanzo.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cloud

import (
	"encoding/json"
)

// checks if the ChatDeleteConvosRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChatDeleteConvosRequest{}

// ChatDeleteConvosRequest struct for ChatDeleteConvosRequest
type ChatDeleteConvosRequest struct {
	Arg *ChatDeleteConvosRequestArg `json:"arg,omitempty"`
}

// NewChatDeleteConvosRequest instantiates a new ChatDeleteConvosRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChatDeleteConvosRequest() *ChatDeleteConvosRequest {
	this := ChatDeleteConvosRequest{}
	return &this
}

// NewChatDeleteConvosRequestWithDefaults instantiates a new ChatDeleteConvosRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChatDeleteConvosRequestWithDefaults() *ChatDeleteConvosRequest {
	this := ChatDeleteConvosRequest{}
	return &this
}

// GetArg returns the Arg field value if set, zero value otherwise.
func (o *ChatDeleteConvosRequest) GetArg() ChatDeleteConvosRequestArg {
	if o == nil || IsNil(o.Arg) {
		var ret ChatDeleteConvosRequestArg
		return ret
	}
	return *o.Arg
}

// GetArgOk returns a tuple with the Arg field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChatDeleteConvosRequest) GetArgOk() (*ChatDeleteConvosRequestArg, bool) {
	if o == nil || IsNil(o.Arg) {
		return nil, false
	}
	return o.Arg, true
}

// HasArg returns a boolean if a field has been set.
func (o *ChatDeleteConvosRequest) HasArg() bool {
	if o != nil && !IsNil(o.Arg) {
		return true
	}

	return false
}

// SetArg gets a reference to the given ChatDeleteConvosRequestArg and assigns it to the Arg field.
func (o *ChatDeleteConvosRequest) SetArg(v ChatDeleteConvosRequestArg) {
	o.Arg = &v
}

func (o ChatDeleteConvosRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChatDeleteConvosRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Arg) {
		toSerialize["arg"] = o.Arg
	}
	return toSerialize, nil
}

type NullableChatDeleteConvosRequest struct {
	value *ChatDeleteConvosRequest
	isSet bool
}

func (v NullableChatDeleteConvosRequest) Get() *ChatDeleteConvosRequest {
	return v.value
}

func (v *NullableChatDeleteConvosRequest) Set(val *ChatDeleteConvosRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableChatDeleteConvosRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableChatDeleteConvosRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChatDeleteConvosRequest(val *ChatDeleteConvosRequest) *NullableChatDeleteConvosRequest {
	return &NullableChatDeleteConvosRequest{value: val, isSet: true}
}

func (v NullableChatDeleteConvosRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChatDeleteConvosRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


