/*
Hanzo Cloud — Unified API

The single unified OpenAPI surface for ALL Hanzo services, aggregated from the per-service specs. Every route is https://api.hanzo.ai/v1/<service>/_*. Regenerated by merge.py — edit the per-service <svc>/openapi.yaml, not this file.

API version: 1.0.0
Contact: support@hanzo.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hanzoai

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
)

// CloudVectorAPIAPIService CloudVectorAPIAPI service
type CloudVectorAPIAPIService service

type CloudVectorAPIAPICloudApiControllerAddVectorRequest struct {
	ctx               context.Context
	ApiService        *CloudVectorAPIAPIService
	cloudObjectVector *CloudObjectVector
}

// The details of the vector
func (r CloudVectorAPIAPICloudApiControllerAddVectorRequest) CloudObjectVector(cloudObjectVector CloudObjectVector) CloudVectorAPIAPICloudApiControllerAddVectorRequest {
	r.cloudObjectVector = &cloudObjectVector
	return r
}

func (r CloudVectorAPIAPICloudApiControllerAddVectorRequest) Execute() (*CloudControllersResponse, *http.Response, error) {
	return r.ApiService.CloudApiControllerAddVectorExecute(r)
}

/*
CloudApiControllerAddVector Api Controller Add Vector

add vector

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return CloudVectorAPIAPICloudApiControllerAddVectorRequest
*/
func (a *CloudVectorAPIAPIService) CloudApiControllerAddVector(ctx context.Context) CloudVectorAPIAPICloudApiControllerAddVectorRequest {
	return CloudVectorAPIAPICloudApiControllerAddVectorRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return CloudControllersResponse
func (a *CloudVectorAPIAPIService) CloudApiControllerAddVectorExecute(r CloudVectorAPIAPICloudApiControllerAddVectorRequest) (*CloudControllersResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPost
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *CloudControllersResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "CloudVectorAPIAPIService.CloudApiControllerAddVector")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/cloud/add-vector"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.cloudObjectVector == nil {
		return localVarReturnValue, nil, reportError("cloudObjectVector is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.cloudObjectVector
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type CloudVectorAPIAPICloudApiControllerDeleteAllVectorsRequest struct {
	ctx        context.Context
	ApiService *CloudVectorAPIAPIService
}

func (r CloudVectorAPIAPICloudApiControllerDeleteAllVectorsRequest) Execute() (*CloudControllersResponse, *http.Response, error) {
	return r.ApiService.CloudApiControllerDeleteAllVectorsExecute(r)
}

/*
CloudApiControllerDeleteAllVectors Api Controller Delete All Vectors

delete all vectors

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return CloudVectorAPIAPICloudApiControllerDeleteAllVectorsRequest
*/
func (a *CloudVectorAPIAPIService) CloudApiControllerDeleteAllVectors(ctx context.Context) CloudVectorAPIAPICloudApiControllerDeleteAllVectorsRequest {
	return CloudVectorAPIAPICloudApiControllerDeleteAllVectorsRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return CloudControllersResponse
func (a *CloudVectorAPIAPIService) CloudApiControllerDeleteAllVectorsExecute(r CloudVectorAPIAPICloudApiControllerDeleteAllVectorsRequest) (*CloudControllersResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPost
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *CloudControllersResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "CloudVectorAPIAPIService.CloudApiControllerDeleteAllVectors")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/cloud/delete-all-vectors"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type CloudVectorAPIAPICloudApiControllerDeleteVectorRequest struct {
	ctx               context.Context
	ApiService        *CloudVectorAPIAPIService
	cloudObjectVector *CloudObjectVector
}

// The details of the vector
func (r CloudVectorAPIAPICloudApiControllerDeleteVectorRequest) CloudObjectVector(cloudObjectVector CloudObjectVector) CloudVectorAPIAPICloudApiControllerDeleteVectorRequest {
	r.cloudObjectVector = &cloudObjectVector
	return r
}

func (r CloudVectorAPIAPICloudApiControllerDeleteVectorRequest) Execute() (*CloudControllersResponse, *http.Response, error) {
	return r.ApiService.CloudApiControllerDeleteVectorExecute(r)
}

/*
CloudApiControllerDeleteVector Api Controller Delete Vector

delete vector

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return CloudVectorAPIAPICloudApiControllerDeleteVectorRequest
*/
func (a *CloudVectorAPIAPIService) CloudApiControllerDeleteVector(ctx context.Context) CloudVectorAPIAPICloudApiControllerDeleteVectorRequest {
	return CloudVectorAPIAPICloudApiControllerDeleteVectorRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return CloudControllersResponse
func (a *CloudVectorAPIAPIService) CloudApiControllerDeleteVectorExecute(r CloudVectorAPIAPICloudApiControllerDeleteVectorRequest) (*CloudControllersResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPost
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *CloudControllersResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "CloudVectorAPIAPIService.CloudApiControllerDeleteVector")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/cloud/delete-vector"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.cloudObjectVector == nil {
		return localVarReturnValue, nil, reportError("cloudObjectVector is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.cloudObjectVector
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type CloudVectorAPIAPICloudApiControllerGetGlobalVectorsRequest struct {
	ctx        context.Context
	ApiService *CloudVectorAPIAPIService
}

func (r CloudVectorAPIAPICloudApiControllerGetGlobalVectorsRequest) Execute() ([]CloudObjectVector, *http.Response, error) {
	return r.ApiService.CloudApiControllerGetGlobalVectorsExecute(r)
}

/*
CloudApiControllerGetGlobalVectors Api Controller Get Global Vectors

get global vectors

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return CloudVectorAPIAPICloudApiControllerGetGlobalVectorsRequest
*/
func (a *CloudVectorAPIAPIService) CloudApiControllerGetGlobalVectors(ctx context.Context) CloudVectorAPIAPICloudApiControllerGetGlobalVectorsRequest {
	return CloudVectorAPIAPICloudApiControllerGetGlobalVectorsRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return []CloudObjectVector
func (a *CloudVectorAPIAPIService) CloudApiControllerGetGlobalVectorsExecute(r CloudVectorAPIAPICloudApiControllerGetGlobalVectorsRequest) ([]CloudObjectVector, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue []CloudObjectVector
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "CloudVectorAPIAPIService.CloudApiControllerGetGlobalVectors")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/cloud/get-global-vectors"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type CloudVectorAPIAPICloudApiControllerGetVectorsRequest struct {
	ctx        context.Context
	ApiService *CloudVectorAPIAPIService
}

func (r CloudVectorAPIAPICloudApiControllerGetVectorsRequest) Execute() ([]CloudObjectVector, *http.Response, error) {
	return r.ApiService.CloudApiControllerGetVectorsExecute(r)
}

/*
CloudApiControllerGetVectors Api Controller Get Vectors

get vectors

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return CloudVectorAPIAPICloudApiControllerGetVectorsRequest
*/
func (a *CloudVectorAPIAPIService) CloudApiControllerGetVectors(ctx context.Context) CloudVectorAPIAPICloudApiControllerGetVectorsRequest {
	return CloudVectorAPIAPICloudApiControllerGetVectorsRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return []CloudObjectVector
func (a *CloudVectorAPIAPIService) CloudApiControllerGetVectorsExecute(r CloudVectorAPIAPICloudApiControllerGetVectorsRequest) ([]CloudObjectVector, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue []CloudObjectVector
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "CloudVectorAPIAPIService.CloudApiControllerGetVectors")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/cloud/get-vectors"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type CloudVectorAPIAPICloudApiControllerUpdateVectorRequest struct {
	ctx               context.Context
	ApiService        *CloudVectorAPIAPIService
	id                *string
	cloudObjectVector *CloudObjectVector
}

// The id (owner/name) of the vector
func (r CloudVectorAPIAPICloudApiControllerUpdateVectorRequest) Id(id string) CloudVectorAPIAPICloudApiControllerUpdateVectorRequest {
	r.id = &id
	return r
}

// The details of the vector
func (r CloudVectorAPIAPICloudApiControllerUpdateVectorRequest) CloudObjectVector(cloudObjectVector CloudObjectVector) CloudVectorAPIAPICloudApiControllerUpdateVectorRequest {
	r.cloudObjectVector = &cloudObjectVector
	return r
}

func (r CloudVectorAPIAPICloudApiControllerUpdateVectorRequest) Execute() (*CloudControllersResponse, *http.Response, error) {
	return r.ApiService.CloudApiControllerUpdateVectorExecute(r)
}

/*
CloudApiControllerUpdateVector Api Controller Update Vector

update vector

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return CloudVectorAPIAPICloudApiControllerUpdateVectorRequest
*/
func (a *CloudVectorAPIAPIService) CloudApiControllerUpdateVector(ctx context.Context) CloudVectorAPIAPICloudApiControllerUpdateVectorRequest {
	return CloudVectorAPIAPICloudApiControllerUpdateVectorRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return CloudControllersResponse
func (a *CloudVectorAPIAPIService) CloudApiControllerUpdateVectorExecute(r CloudVectorAPIAPICloudApiControllerUpdateVectorRequest) (*CloudControllersResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPost
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *CloudControllersResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "CloudVectorAPIAPIService.CloudApiControllerUpdateVector")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/cloud/update-vector"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.id == nil {
		return localVarReturnValue, nil, reportError("id is required and must be specified")
	}
	if r.cloudObjectVector == nil {
		return localVarReturnValue, nil, reportError("cloudObjectVector is required and must be specified")
	}

	parameterAddToHeaderOrQuery(localVarQueryParams, "id", r.id, "form", "")
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.cloudObjectVector
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type CloudVectorAPIAPICloudProductControllerVectorStatsRequest struct {
	ctx        context.Context
	ApiService *CloudVectorAPIAPIService
}

func (r CloudVectorAPIAPICloudProductControllerVectorStatsRequest) Execute() (*CloudProductControllerVectorStats200Response, *http.Response, error) {
	return r.ApiService.CloudProductControllerVectorStatsExecute(r)
}

/*
CloudProductControllerVectorStats Method for CloudProductControllerVectorStats

Aggregate vector stats — collection count, total vectors, total storage bytes.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return CloudVectorAPIAPICloudProductControllerVectorStatsRequest
*/
func (a *CloudVectorAPIAPIService) CloudProductControllerVectorStats(ctx context.Context) CloudVectorAPIAPICloudProductControllerVectorStatsRequest {
	return CloudVectorAPIAPICloudProductControllerVectorStatsRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return CloudProductControllerVectorStats200Response
func (a *CloudVectorAPIAPIService) CloudProductControllerVectorStatsExecute(r CloudVectorAPIAPICloudProductControllerVectorStatsRequest) (*CloudProductControllerVectorStats200Response, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *CloudProductControllerVectorStats200Response
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "CloudVectorAPIAPIService.CloudProductControllerVectorStats")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/vector/stats"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
