/*
Hanzo Cloud — Unified API

The single unified OpenAPI surface for ALL Hanzo services, aggregated from the per-service specs. Every route is https://api.hanzo.ai/v1/<service>/_*. Regenerated by merge.py — edit the per-service <svc>/openapi.yaml, not this file.

API version: 1.0.0
Contact: support@hanzo.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hanzoai

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
)

// NexusArticleAPIAPIService NexusArticleAPIAPI service
type NexusArticleAPIAPIService service

type NexusArticleAPIAPINexusAddArticleRequest struct {
	ctx          context.Context
	ApiService   *NexusArticleAPIAPIService
	nexusArticle *NexusArticle
}

// The details of the article
func (r NexusArticleAPIAPINexusAddArticleRequest) NexusArticle(nexusArticle NexusArticle) NexusArticleAPIAPINexusAddArticleRequest {
	r.nexusArticle = &nexusArticle
	return r
}

func (r NexusArticleAPIAPINexusAddArticleRequest) Execute() (*NexusResponse, *http.Response, error) {
	return r.ApiService.NexusAddArticleExecute(r)
}

/*
NexusAddArticle add Article

Add an article

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return NexusArticleAPIAPINexusAddArticleRequest
*/
func (a *NexusArticleAPIAPIService) NexusAddArticle(ctx context.Context) NexusArticleAPIAPINexusAddArticleRequest {
	return NexusArticleAPIAPINexusAddArticleRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return NexusResponse
func (a *NexusArticleAPIAPIService) NexusAddArticleExecute(r NexusArticleAPIAPINexusAddArticleRequest) (*NexusResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPost
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *NexusResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "NexusArticleAPIAPIService.NexusAddArticle")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/nexus/add-article"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.nexusArticle == nil {
		return localVarReturnValue, nil, reportError("nexusArticle is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.nexusArticle
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type NexusArticleAPIAPINexusDeleteArticleRequest struct {
	ctx          context.Context
	ApiService   *NexusArticleAPIAPIService
	nexusArticle *NexusArticle
}

// The details of the article
func (r NexusArticleAPIAPINexusDeleteArticleRequest) NexusArticle(nexusArticle NexusArticle) NexusArticleAPIAPINexusDeleteArticleRequest {
	r.nexusArticle = &nexusArticle
	return r
}

func (r NexusArticleAPIAPINexusDeleteArticleRequest) Execute() (*NexusResponse, *http.Response, error) {
	return r.ApiService.NexusDeleteArticleExecute(r)
}

/*
NexusDeleteArticle delete Article

Delete an article

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return NexusArticleAPIAPINexusDeleteArticleRequest
*/
func (a *NexusArticleAPIAPIService) NexusDeleteArticle(ctx context.Context) NexusArticleAPIAPINexusDeleteArticleRequest {
	return NexusArticleAPIAPINexusDeleteArticleRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return NexusResponse
func (a *NexusArticleAPIAPIService) NexusDeleteArticleExecute(r NexusArticleAPIAPINexusDeleteArticleRequest) (*NexusResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPost
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *NexusResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "NexusArticleAPIAPIService.NexusDeleteArticle")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/nexus/delete-article"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.nexusArticle == nil {
		return localVarReturnValue, nil, reportError("nexusArticle is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.nexusArticle
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type NexusArticleAPIAPINexusGetArticleRequest struct {
	ctx        context.Context
	ApiService *NexusArticleAPIAPIService
	id         *string
}

// The id (owner/name) of the article
func (r NexusArticleAPIAPINexusGetArticleRequest) Id(id string) NexusArticleAPIAPINexusGetArticleRequest {
	r.id = &id
	return r
}

func (r NexusArticleAPIAPINexusGetArticleRequest) Execute() (*NexusArticle, *http.Response, error) {
	return r.ApiService.NexusGetArticleExecute(r)
}

/*
NexusGetArticle get Article

Get an article

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return NexusArticleAPIAPINexusGetArticleRequest
*/
func (a *NexusArticleAPIAPIService) NexusGetArticle(ctx context.Context) NexusArticleAPIAPINexusGetArticleRequest {
	return NexusArticleAPIAPINexusGetArticleRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return NexusArticle
func (a *NexusArticleAPIAPIService) NexusGetArticleExecute(r NexusArticleAPIAPINexusGetArticleRequest) (*NexusArticle, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *NexusArticle
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "NexusArticleAPIAPIService.NexusGetArticle")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/nexus/get-article"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.id == nil {
		return localVarReturnValue, nil, reportError("id is required and must be specified")
	}

	parameterAddToHeaderOrQuery(localVarQueryParams, "id", r.id, "form", "")
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type NexusArticleAPIAPINexusGetArticlesRequest struct {
	ctx        context.Context
	ApiService *NexusArticleAPIAPIService
	owner      *string
}

// The owner of the articles
func (r NexusArticleAPIAPINexusGetArticlesRequest) Owner(owner string) NexusArticleAPIAPINexusGetArticlesRequest {
	r.owner = &owner
	return r
}

func (r NexusArticleAPIAPINexusGetArticlesRequest) Execute() ([]NexusArticle, *http.Response, error) {
	return r.ApiService.NexusGetArticlesExecute(r)
}

/*
NexusGetArticles get Articles

Get articles

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return NexusArticleAPIAPINexusGetArticlesRequest
*/
func (a *NexusArticleAPIAPIService) NexusGetArticles(ctx context.Context) NexusArticleAPIAPINexusGetArticlesRequest {
	return NexusArticleAPIAPINexusGetArticlesRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return []NexusArticle
func (a *NexusArticleAPIAPIService) NexusGetArticlesExecute(r NexusArticleAPIAPINexusGetArticlesRequest) ([]NexusArticle, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue []NexusArticle
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "NexusArticleAPIAPIService.NexusGetArticles")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/nexus/get-articles"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.owner == nil {
		return localVarReturnValue, nil, reportError("owner is required and must be specified")
	}

	parameterAddToHeaderOrQuery(localVarQueryParams, "owner", r.owner, "form", "")
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type NexusArticleAPIAPINexusGetGlobalArticlesRequest struct {
	ctx        context.Context
	ApiService *NexusArticleAPIAPIService
}

func (r NexusArticleAPIAPINexusGetGlobalArticlesRequest) Execute() ([]NexusArticle, *http.Response, error) {
	return r.ApiService.NexusGetGlobalArticlesExecute(r)
}

/*
NexusGetGlobalArticles get Global Articles

Get global articles

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return NexusArticleAPIAPINexusGetGlobalArticlesRequest
*/
func (a *NexusArticleAPIAPIService) NexusGetGlobalArticles(ctx context.Context) NexusArticleAPIAPINexusGetGlobalArticlesRequest {
	return NexusArticleAPIAPINexusGetGlobalArticlesRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return []NexusArticle
func (a *NexusArticleAPIAPIService) NexusGetGlobalArticlesExecute(r NexusArticleAPIAPINexusGetGlobalArticlesRequest) ([]NexusArticle, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue []NexusArticle
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "NexusArticleAPIAPIService.NexusGetGlobalArticles")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/nexus/get-global-articles"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type NexusArticleAPIAPINexusUpdateArticleRequest struct {
	ctx          context.Context
	ApiService   *NexusArticleAPIAPIService
	id           *string
	nexusArticle *NexusArticle
}

// The id (owner/name) of the article
func (r NexusArticleAPIAPINexusUpdateArticleRequest) Id(id string) NexusArticleAPIAPINexusUpdateArticleRequest {
	r.id = &id
	return r
}

// The details of the article
func (r NexusArticleAPIAPINexusUpdateArticleRequest) NexusArticle(nexusArticle NexusArticle) NexusArticleAPIAPINexusUpdateArticleRequest {
	r.nexusArticle = &nexusArticle
	return r
}

func (r NexusArticleAPIAPINexusUpdateArticleRequest) Execute() (*NexusResponse, *http.Response, error) {
	return r.ApiService.NexusUpdateArticleExecute(r)
}

/*
NexusUpdateArticle update Article

Update an article

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return NexusArticleAPIAPINexusUpdateArticleRequest
*/
func (a *NexusArticleAPIAPIService) NexusUpdateArticle(ctx context.Context) NexusArticleAPIAPINexusUpdateArticleRequest {
	return NexusArticleAPIAPINexusUpdateArticleRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return NexusResponse
func (a *NexusArticleAPIAPIService) NexusUpdateArticleExecute(r NexusArticleAPIAPINexusUpdateArticleRequest) (*NexusResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPost
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *NexusResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "NexusArticleAPIAPIService.NexusUpdateArticle")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/nexus/update-article"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.id == nil {
		return localVarReturnValue, nil, reportError("id is required and must be specified")
	}
	if r.nexusArticle == nil {
		return localVarReturnValue, nil, reportError("nexusArticle is required and must be specified")
	}

	parameterAddToHeaderOrQuery(localVarQueryParams, "id", r.id, "form", "")
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.nexusArticle
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
