/*
Hanzo Cloud — Unified API

The single unified OpenAPI surface for ALL Hanzo services, aggregated from the per-service specs. Every route is https://api.hanzo.ai/v1/<service>/_*. Regenerated by merge.py — edit the per-service <svc>/openapi.yaml, not this file.

API version: 1.0.0
Contact: support@hanzo.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hanzoai

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the PlatformApplicationSaveDockerProviderRequestJson type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PlatformApplicationSaveDockerProviderRequestJson{}

// PlatformApplicationSaveDockerProviderRequestJson struct for PlatformApplicationSaveDockerProviderRequestJson
type PlatformApplicationSaveDockerProviderRequestJson struct {
	ApplicationId string  `json:"applicationId"`
	DockerImage   string  `json:"dockerImage"`
	Username      *string `json:"username,omitempty"`
	Password      *string `json:"password,omitempty"`
	RegistryUrl   *string `json:"registryUrl,omitempty"`
}

type _PlatformApplicationSaveDockerProviderRequestJson PlatformApplicationSaveDockerProviderRequestJson

// NewPlatformApplicationSaveDockerProviderRequestJson instantiates a new PlatformApplicationSaveDockerProviderRequestJson object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlatformApplicationSaveDockerProviderRequestJson(applicationId string, dockerImage string) *PlatformApplicationSaveDockerProviderRequestJson {
	this := PlatformApplicationSaveDockerProviderRequestJson{}
	this.ApplicationId = applicationId
	this.DockerImage = dockerImage
	return &this
}

// NewPlatformApplicationSaveDockerProviderRequestJsonWithDefaults instantiates a new PlatformApplicationSaveDockerProviderRequestJson object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlatformApplicationSaveDockerProviderRequestJsonWithDefaults() *PlatformApplicationSaveDockerProviderRequestJson {
	this := PlatformApplicationSaveDockerProviderRequestJson{}
	return &this
}

// GetApplicationId returns the ApplicationId field value
func (o *PlatformApplicationSaveDockerProviderRequestJson) GetApplicationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ApplicationId
}

// GetApplicationIdOk returns a tuple with the ApplicationId field value
// and a boolean to check if the value has been set.
func (o *PlatformApplicationSaveDockerProviderRequestJson) GetApplicationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApplicationId, true
}

// SetApplicationId sets field value
func (o *PlatformApplicationSaveDockerProviderRequestJson) SetApplicationId(v string) {
	o.ApplicationId = v
}

// GetDockerImage returns the DockerImage field value
func (o *PlatformApplicationSaveDockerProviderRequestJson) GetDockerImage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DockerImage
}

// GetDockerImageOk returns a tuple with the DockerImage field value
// and a boolean to check if the value has been set.
func (o *PlatformApplicationSaveDockerProviderRequestJson) GetDockerImageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DockerImage, true
}

// SetDockerImage sets field value
func (o *PlatformApplicationSaveDockerProviderRequestJson) SetDockerImage(v string) {
	o.DockerImage = v
}

// GetUsername returns the Username field value if set, zero value otherwise.
func (o *PlatformApplicationSaveDockerProviderRequestJson) GetUsername() string {
	if o == nil || IsNil(o.Username) {
		var ret string
		return ret
	}
	return *o.Username
}

// GetUsernameOk returns a tuple with the Username field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlatformApplicationSaveDockerProviderRequestJson) GetUsernameOk() (*string, bool) {
	if o == nil || IsNil(o.Username) {
		return nil, false
	}
	return o.Username, true
}

// HasUsername returns a boolean if a field has been set.
func (o *PlatformApplicationSaveDockerProviderRequestJson) HasUsername() bool {
	if o != nil && !IsNil(o.Username) {
		return true
	}

	return false
}

// SetUsername gets a reference to the given string and assigns it to the Username field.
func (o *PlatformApplicationSaveDockerProviderRequestJson) SetUsername(v string) {
	o.Username = &v
}

// GetPassword returns the Password field value if set, zero value otherwise.
func (o *PlatformApplicationSaveDockerProviderRequestJson) GetPassword() string {
	if o == nil || IsNil(o.Password) {
		var ret string
		return ret
	}
	return *o.Password
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlatformApplicationSaveDockerProviderRequestJson) GetPasswordOk() (*string, bool) {
	if o == nil || IsNil(o.Password) {
		return nil, false
	}
	return o.Password, true
}

// HasPassword returns a boolean if a field has been set.
func (o *PlatformApplicationSaveDockerProviderRequestJson) HasPassword() bool {
	if o != nil && !IsNil(o.Password) {
		return true
	}

	return false
}

// SetPassword gets a reference to the given string and assigns it to the Password field.
func (o *PlatformApplicationSaveDockerProviderRequestJson) SetPassword(v string) {
	o.Password = &v
}

// GetRegistryUrl returns the RegistryUrl field value if set, zero value otherwise.
func (o *PlatformApplicationSaveDockerProviderRequestJson) GetRegistryUrl() string {
	if o == nil || IsNil(o.RegistryUrl) {
		var ret string
		return ret
	}
	return *o.RegistryUrl
}

// GetRegistryUrlOk returns a tuple with the RegistryUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlatformApplicationSaveDockerProviderRequestJson) GetRegistryUrlOk() (*string, bool) {
	if o == nil || IsNil(o.RegistryUrl) {
		return nil, false
	}
	return o.RegistryUrl, true
}

// HasRegistryUrl returns a boolean if a field has been set.
func (o *PlatformApplicationSaveDockerProviderRequestJson) HasRegistryUrl() bool {
	if o != nil && !IsNil(o.RegistryUrl) {
		return true
	}

	return false
}

// SetRegistryUrl gets a reference to the given string and assigns it to the RegistryUrl field.
func (o *PlatformApplicationSaveDockerProviderRequestJson) SetRegistryUrl(v string) {
	o.RegistryUrl = &v
}

func (o PlatformApplicationSaveDockerProviderRequestJson) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PlatformApplicationSaveDockerProviderRequestJson) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["applicationId"] = o.ApplicationId
	toSerialize["dockerImage"] = o.DockerImage
	if !IsNil(o.Username) {
		toSerialize["username"] = o.Username
	}
	if !IsNil(o.Password) {
		toSerialize["password"] = o.Password
	}
	if !IsNil(o.RegistryUrl) {
		toSerialize["registryUrl"] = o.RegistryUrl
	}
	return toSerialize, nil
}

func (o *PlatformApplicationSaveDockerProviderRequestJson) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"applicationId",
		"dockerImage",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPlatformApplicationSaveDockerProviderRequestJson := _PlatformApplicationSaveDockerProviderRequestJson{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPlatformApplicationSaveDockerProviderRequestJson)

	if err != nil {
		return err
	}

	*o = PlatformApplicationSaveDockerProviderRequestJson(varPlatformApplicationSaveDockerProviderRequestJson)

	return err
}

type NullablePlatformApplicationSaveDockerProviderRequestJson struct {
	value *PlatformApplicationSaveDockerProviderRequestJson
	isSet bool
}

func (v NullablePlatformApplicationSaveDockerProviderRequestJson) Get() *PlatformApplicationSaveDockerProviderRequestJson {
	return v.value
}

func (v *NullablePlatformApplicationSaveDockerProviderRequestJson) Set(val *PlatformApplicationSaveDockerProviderRequestJson) {
	v.value = val
	v.isSet = true
}

func (v NullablePlatformApplicationSaveDockerProviderRequestJson) IsSet() bool {
	return v.isSet
}

func (v *NullablePlatformApplicationSaveDockerProviderRequestJson) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlatformApplicationSaveDockerProviderRequestJson(val *PlatformApplicationSaveDockerProviderRequestJson) *NullablePlatformApplicationSaveDockerProviderRequestJson {
	return &NullablePlatformApplicationSaveDockerProviderRequestJson{value: val, isSet: true}
}

func (v NullablePlatformApplicationSaveDockerProviderRequestJson) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePlatformApplicationSaveDockerProviderRequestJson) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
