/*
Hanzo Cloud API

The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator's admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hanzoai

import (
	"encoding/json"
)

// checks if the CaptableShareClassIn type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CaptableShareClassIn{}

// CaptableShareClassIn struct for CaptableShareClassIn
type CaptableShareClassIn struct {
	BoardApprovalDate             interface{} `json:"boardApprovalDate,omitempty"`
	ClassType                     interface{} `json:"classType,omitempty"`
	ConversionRights              interface{} `json:"conversionRights,omitempty"`
	ConvertsToShareClassId        interface{} `json:"convertsToShareClassId,omitempty"`
	InitialSharesAuthorized       interface{} `json:"initialSharesAuthorized,omitempty"`
	LiquidationPreferenceMultiple interface{} `json:"liquidationPreferenceMultiple,omitempty"`
	Name                          interface{} `json:"name,omitempty"`
	ParValue                      interface{} `json:"parValue,omitempty"`
	ParticipationCapMultiple      interface{} `json:"participationCapMultiple,omitempty"`
	PricePerShare                 interface{} `json:"pricePerShare,omitempty"`
	Seniority                     interface{} `json:"seniority,omitempty"`
	StockholderApprovalDate       interface{} `json:"stockholderApprovalDate,omitempty"`
	VotesPerShare                 interface{} `json:"votesPerShare,omitempty"`
}

// NewCaptableShareClassIn instantiates a new CaptableShareClassIn object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCaptableShareClassIn() *CaptableShareClassIn {
	this := CaptableShareClassIn{}
	return &this
}

// NewCaptableShareClassInWithDefaults instantiates a new CaptableShareClassIn object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCaptableShareClassInWithDefaults() *CaptableShareClassIn {
	this := CaptableShareClassIn{}
	return &this
}

// GetBoardApprovalDate returns the BoardApprovalDate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CaptableShareClassIn) GetBoardApprovalDate() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.BoardApprovalDate
}

// GetBoardApprovalDateOk returns a tuple with the BoardApprovalDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CaptableShareClassIn) GetBoardApprovalDateOk() (*interface{}, bool) {
	if o == nil || IsNil(o.BoardApprovalDate) {
		return nil, false
	}
	return &o.BoardApprovalDate, true
}

// HasBoardApprovalDate returns a boolean if a field has been set.
func (o *CaptableShareClassIn) HasBoardApprovalDate() bool {
	if o != nil && !IsNil(o.BoardApprovalDate) {
		return true
	}

	return false
}

// SetBoardApprovalDate gets a reference to the given interface{} and assigns it to the BoardApprovalDate field.
func (o *CaptableShareClassIn) SetBoardApprovalDate(v interface{}) {
	o.BoardApprovalDate = v
}

// GetClassType returns the ClassType field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CaptableShareClassIn) GetClassType() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.ClassType
}

// GetClassTypeOk returns a tuple with the ClassType field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CaptableShareClassIn) GetClassTypeOk() (*interface{}, bool) {
	if o == nil || IsNil(o.ClassType) {
		return nil, false
	}
	return &o.ClassType, true
}

// HasClassType returns a boolean if a field has been set.
func (o *CaptableShareClassIn) HasClassType() bool {
	if o != nil && !IsNil(o.ClassType) {
		return true
	}

	return false
}

// SetClassType gets a reference to the given interface{} and assigns it to the ClassType field.
func (o *CaptableShareClassIn) SetClassType(v interface{}) {
	o.ClassType = v
}

// GetConversionRights returns the ConversionRights field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CaptableShareClassIn) GetConversionRights() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.ConversionRights
}

// GetConversionRightsOk returns a tuple with the ConversionRights field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CaptableShareClassIn) GetConversionRightsOk() (*interface{}, bool) {
	if o == nil || IsNil(o.ConversionRights) {
		return nil, false
	}
	return &o.ConversionRights, true
}

// HasConversionRights returns a boolean if a field has been set.
func (o *CaptableShareClassIn) HasConversionRights() bool {
	if o != nil && !IsNil(o.ConversionRights) {
		return true
	}

	return false
}

// SetConversionRights gets a reference to the given interface{} and assigns it to the ConversionRights field.
func (o *CaptableShareClassIn) SetConversionRights(v interface{}) {
	o.ConversionRights = v
}

// GetConvertsToShareClassId returns the ConvertsToShareClassId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CaptableShareClassIn) GetConvertsToShareClassId() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.ConvertsToShareClassId
}

// GetConvertsToShareClassIdOk returns a tuple with the ConvertsToShareClassId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CaptableShareClassIn) GetConvertsToShareClassIdOk() (*interface{}, bool) {
	if o == nil || IsNil(o.ConvertsToShareClassId) {
		return nil, false
	}
	return &o.ConvertsToShareClassId, true
}

// HasConvertsToShareClassId returns a boolean if a field has been set.
func (o *CaptableShareClassIn) HasConvertsToShareClassId() bool {
	if o != nil && !IsNil(o.ConvertsToShareClassId) {
		return true
	}

	return false
}

// SetConvertsToShareClassId gets a reference to the given interface{} and assigns it to the ConvertsToShareClassId field.
func (o *CaptableShareClassIn) SetConvertsToShareClassId(v interface{}) {
	o.ConvertsToShareClassId = v
}

// GetInitialSharesAuthorized returns the InitialSharesAuthorized field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CaptableShareClassIn) GetInitialSharesAuthorized() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.InitialSharesAuthorized
}

// GetInitialSharesAuthorizedOk returns a tuple with the InitialSharesAuthorized field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CaptableShareClassIn) GetInitialSharesAuthorizedOk() (*interface{}, bool) {
	if o == nil || IsNil(o.InitialSharesAuthorized) {
		return nil, false
	}
	return &o.InitialSharesAuthorized, true
}

// HasInitialSharesAuthorized returns a boolean if a field has been set.
func (o *CaptableShareClassIn) HasInitialSharesAuthorized() bool {
	if o != nil && !IsNil(o.InitialSharesAuthorized) {
		return true
	}

	return false
}

// SetInitialSharesAuthorized gets a reference to the given interface{} and assigns it to the InitialSharesAuthorized field.
func (o *CaptableShareClassIn) SetInitialSharesAuthorized(v interface{}) {
	o.InitialSharesAuthorized = v
}

// GetLiquidationPreferenceMultiple returns the LiquidationPreferenceMultiple field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CaptableShareClassIn) GetLiquidationPreferenceMultiple() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.LiquidationPreferenceMultiple
}

// GetLiquidationPreferenceMultipleOk returns a tuple with the LiquidationPreferenceMultiple field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CaptableShareClassIn) GetLiquidationPreferenceMultipleOk() (*interface{}, bool) {
	if o == nil || IsNil(o.LiquidationPreferenceMultiple) {
		return nil, false
	}
	return &o.LiquidationPreferenceMultiple, true
}

// HasLiquidationPreferenceMultiple returns a boolean if a field has been set.
func (o *CaptableShareClassIn) HasLiquidationPreferenceMultiple() bool {
	if o != nil && !IsNil(o.LiquidationPreferenceMultiple) {
		return true
	}

	return false
}

// SetLiquidationPreferenceMultiple gets a reference to the given interface{} and assigns it to the LiquidationPreferenceMultiple field.
func (o *CaptableShareClassIn) SetLiquidationPreferenceMultiple(v interface{}) {
	o.LiquidationPreferenceMultiple = v
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CaptableShareClassIn) GetName() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CaptableShareClassIn) GetNameOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return &o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CaptableShareClassIn) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given interface{} and assigns it to the Name field.
func (o *CaptableShareClassIn) SetName(v interface{}) {
	o.Name = v
}

// GetParValue returns the ParValue field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CaptableShareClassIn) GetParValue() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.ParValue
}

// GetParValueOk returns a tuple with the ParValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CaptableShareClassIn) GetParValueOk() (*interface{}, bool) {
	if o == nil || IsNil(o.ParValue) {
		return nil, false
	}
	return &o.ParValue, true
}

// HasParValue returns a boolean if a field has been set.
func (o *CaptableShareClassIn) HasParValue() bool {
	if o != nil && !IsNil(o.ParValue) {
		return true
	}

	return false
}

// SetParValue gets a reference to the given interface{} and assigns it to the ParValue field.
func (o *CaptableShareClassIn) SetParValue(v interface{}) {
	o.ParValue = v
}

// GetParticipationCapMultiple returns the ParticipationCapMultiple field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CaptableShareClassIn) GetParticipationCapMultiple() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.ParticipationCapMultiple
}

// GetParticipationCapMultipleOk returns a tuple with the ParticipationCapMultiple field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CaptableShareClassIn) GetParticipationCapMultipleOk() (*interface{}, bool) {
	if o == nil || IsNil(o.ParticipationCapMultiple) {
		return nil, false
	}
	return &o.ParticipationCapMultiple, true
}

// HasParticipationCapMultiple returns a boolean if a field has been set.
func (o *CaptableShareClassIn) HasParticipationCapMultiple() bool {
	if o != nil && !IsNil(o.ParticipationCapMultiple) {
		return true
	}

	return false
}

// SetParticipationCapMultiple gets a reference to the given interface{} and assigns it to the ParticipationCapMultiple field.
func (o *CaptableShareClassIn) SetParticipationCapMultiple(v interface{}) {
	o.ParticipationCapMultiple = v
}

// GetPricePerShare returns the PricePerShare field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CaptableShareClassIn) GetPricePerShare() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.PricePerShare
}

// GetPricePerShareOk returns a tuple with the PricePerShare field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CaptableShareClassIn) GetPricePerShareOk() (*interface{}, bool) {
	if o == nil || IsNil(o.PricePerShare) {
		return nil, false
	}
	return &o.PricePerShare, true
}

// HasPricePerShare returns a boolean if a field has been set.
func (o *CaptableShareClassIn) HasPricePerShare() bool {
	if o != nil && !IsNil(o.PricePerShare) {
		return true
	}

	return false
}

// SetPricePerShare gets a reference to the given interface{} and assigns it to the PricePerShare field.
func (o *CaptableShareClassIn) SetPricePerShare(v interface{}) {
	o.PricePerShare = v
}

// GetSeniority returns the Seniority field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CaptableShareClassIn) GetSeniority() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Seniority
}

// GetSeniorityOk returns a tuple with the Seniority field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CaptableShareClassIn) GetSeniorityOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Seniority) {
		return nil, false
	}
	return &o.Seniority, true
}

// HasSeniority returns a boolean if a field has been set.
func (o *CaptableShareClassIn) HasSeniority() bool {
	if o != nil && !IsNil(o.Seniority) {
		return true
	}

	return false
}

// SetSeniority gets a reference to the given interface{} and assigns it to the Seniority field.
func (o *CaptableShareClassIn) SetSeniority(v interface{}) {
	o.Seniority = v
}

// GetStockholderApprovalDate returns the StockholderApprovalDate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CaptableShareClassIn) GetStockholderApprovalDate() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.StockholderApprovalDate
}

// GetStockholderApprovalDateOk returns a tuple with the StockholderApprovalDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CaptableShareClassIn) GetStockholderApprovalDateOk() (*interface{}, bool) {
	if o == nil || IsNil(o.StockholderApprovalDate) {
		return nil, false
	}
	return &o.StockholderApprovalDate, true
}

// HasStockholderApprovalDate returns a boolean if a field has been set.
func (o *CaptableShareClassIn) HasStockholderApprovalDate() bool {
	if o != nil && !IsNil(o.StockholderApprovalDate) {
		return true
	}

	return false
}

// SetStockholderApprovalDate gets a reference to the given interface{} and assigns it to the StockholderApprovalDate field.
func (o *CaptableShareClassIn) SetStockholderApprovalDate(v interface{}) {
	o.StockholderApprovalDate = v
}

// GetVotesPerShare returns the VotesPerShare field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CaptableShareClassIn) GetVotesPerShare() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.VotesPerShare
}

// GetVotesPerShareOk returns a tuple with the VotesPerShare field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CaptableShareClassIn) GetVotesPerShareOk() (*interface{}, bool) {
	if o == nil || IsNil(o.VotesPerShare) {
		return nil, false
	}
	return &o.VotesPerShare, true
}

// HasVotesPerShare returns a boolean if a field has been set.
func (o *CaptableShareClassIn) HasVotesPerShare() bool {
	if o != nil && !IsNil(o.VotesPerShare) {
		return true
	}

	return false
}

// SetVotesPerShare gets a reference to the given interface{} and assigns it to the VotesPerShare field.
func (o *CaptableShareClassIn) SetVotesPerShare(v interface{}) {
	o.VotesPerShare = v
}

func (o CaptableShareClassIn) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CaptableShareClassIn) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.BoardApprovalDate != nil {
		toSerialize["boardApprovalDate"] = o.BoardApprovalDate
	}
	if o.ClassType != nil {
		toSerialize["classType"] = o.ClassType
	}
	if o.ConversionRights != nil {
		toSerialize["conversionRights"] = o.ConversionRights
	}
	if o.ConvertsToShareClassId != nil {
		toSerialize["convertsToShareClassId"] = o.ConvertsToShareClassId
	}
	if o.InitialSharesAuthorized != nil {
		toSerialize["initialSharesAuthorized"] = o.InitialSharesAuthorized
	}
	if o.LiquidationPreferenceMultiple != nil {
		toSerialize["liquidationPreferenceMultiple"] = o.LiquidationPreferenceMultiple
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.ParValue != nil {
		toSerialize["parValue"] = o.ParValue
	}
	if o.ParticipationCapMultiple != nil {
		toSerialize["participationCapMultiple"] = o.ParticipationCapMultiple
	}
	if o.PricePerShare != nil {
		toSerialize["pricePerShare"] = o.PricePerShare
	}
	if o.Seniority != nil {
		toSerialize["seniority"] = o.Seniority
	}
	if o.StockholderApprovalDate != nil {
		toSerialize["stockholderApprovalDate"] = o.StockholderApprovalDate
	}
	if o.VotesPerShare != nil {
		toSerialize["votesPerShare"] = o.VotesPerShare
	}
	return toSerialize, nil
}

type NullableCaptableShareClassIn struct {
	value *CaptableShareClassIn
	isSet bool
}

func (v NullableCaptableShareClassIn) Get() *CaptableShareClassIn {
	return v.value
}

func (v *NullableCaptableShareClassIn) Set(val *CaptableShareClassIn) {
	v.value = val
	v.isSet = true
}

func (v NullableCaptableShareClassIn) IsSet() bool {
	return v.isSet
}

func (v *NullableCaptableShareClassIn) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCaptableShareClassIn(val *CaptableShareClassIn) *NullableCaptableShareClassIn {
	return &NullableCaptableShareClassIn{value: val, isSet: true}
}

func (v NullableCaptableShareClassIn) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCaptableShareClassIn) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
