/*
Hanzo Cloud API

The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator's admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hanzoai

import (
	"encoding/json"
)

// checks if the BillingInvoice type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BillingInvoice{}

// BillingInvoice struct for BillingInvoice
type BillingInvoice struct {
	AmountDue     *int32  `json:"amountDue,omitempty"`
	AmountPaid    *int32  `json:"amountPaid,omitempty"`
	AttemptCount  *int32  `json:"attemptCount,omitempty"`
	CreatedAt     *string `json:"createdAt,omitempty"`
	CreditApplied *int32  `json:"creditApplied,omitempty"`
	Currency      *string `json:"currency,omitempty"`
	CustomerEmail *string `json:"customerEmail,omitempty"`
	Discount      *int32  `json:"discount,omitempty"`
	DueDate       *string `json:"dueDate,omitempty"`
	Id            *string `json:"id,omitempty"`
	// LineItems carries no omitempty and is never allocated empty, because the wire it reproduces sends `null` for an invoice with no lines. An empty array there would be a different answer to \"were there lines\".
	LineItems      []InvoiceLineItem `json:"lineItems,omitempty"`
	Number         *int32            `json:"number,omitempty"`
	NumberStr      *string           `json:"numberStr,omitempty"`
	PaidAt         *string           `json:"paidAt,omitempty"`
	PaymentMethod  *string           `json:"paymentMethod,omitempty"`
	PaymentRef     *string           `json:"paymentRef,omitempty"`
	PeriodEnd      *string           `json:"periodEnd,omitempty"`
	PeriodStart    *string           `json:"periodStart,omitempty"`
	Status         *string           `json:"status,omitempty"`
	SubscriptionId *string           `json:"subscriptionId,omitempty"`
	Subtotal       *int32            `json:"subtotal,omitempty"`
	Tax            *int32            `json:"tax,omitempty"`
	UpdatedAt      *string           `json:"updatedAt,omitempty"`
	UserId         *string           `json:"userId,omitempty"`
	VoidedAt       *string           `json:"voidedAt,omitempty"`
}

// NewBillingInvoice instantiates a new BillingInvoice object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBillingInvoice() *BillingInvoice {
	this := BillingInvoice{}
	return &this
}

// NewBillingInvoiceWithDefaults instantiates a new BillingInvoice object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBillingInvoiceWithDefaults() *BillingInvoice {
	this := BillingInvoice{}
	return &this
}

// GetAmountDue returns the AmountDue field value if set, zero value otherwise.
func (o *BillingInvoice) GetAmountDue() int32 {
	if o == nil || IsNil(o.AmountDue) {
		var ret int32
		return ret
	}
	return *o.AmountDue
}

// GetAmountDueOk returns a tuple with the AmountDue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillingInvoice) GetAmountDueOk() (*int32, bool) {
	if o == nil || IsNil(o.AmountDue) {
		return nil, false
	}
	return o.AmountDue, true
}

// HasAmountDue returns a boolean if a field has been set.
func (o *BillingInvoice) HasAmountDue() bool {
	if o != nil && !IsNil(o.AmountDue) {
		return true
	}

	return false
}

// SetAmountDue gets a reference to the given int32 and assigns it to the AmountDue field.
func (o *BillingInvoice) SetAmountDue(v int32) {
	o.AmountDue = &v
}

// GetAmountPaid returns the AmountPaid field value if set, zero value otherwise.
func (o *BillingInvoice) GetAmountPaid() int32 {
	if o == nil || IsNil(o.AmountPaid) {
		var ret int32
		return ret
	}
	return *o.AmountPaid
}

// GetAmountPaidOk returns a tuple with the AmountPaid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillingInvoice) GetAmountPaidOk() (*int32, bool) {
	if o == nil || IsNil(o.AmountPaid) {
		return nil, false
	}
	return o.AmountPaid, true
}

// HasAmountPaid returns a boolean if a field has been set.
func (o *BillingInvoice) HasAmountPaid() bool {
	if o != nil && !IsNil(o.AmountPaid) {
		return true
	}

	return false
}

// SetAmountPaid gets a reference to the given int32 and assigns it to the AmountPaid field.
func (o *BillingInvoice) SetAmountPaid(v int32) {
	o.AmountPaid = &v
}

// GetAttemptCount returns the AttemptCount field value if set, zero value otherwise.
func (o *BillingInvoice) GetAttemptCount() int32 {
	if o == nil || IsNil(o.AttemptCount) {
		var ret int32
		return ret
	}
	return *o.AttemptCount
}

// GetAttemptCountOk returns a tuple with the AttemptCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillingInvoice) GetAttemptCountOk() (*int32, bool) {
	if o == nil || IsNil(o.AttemptCount) {
		return nil, false
	}
	return o.AttemptCount, true
}

// HasAttemptCount returns a boolean if a field has been set.
func (o *BillingInvoice) HasAttemptCount() bool {
	if o != nil && !IsNil(o.AttemptCount) {
		return true
	}

	return false
}

// SetAttemptCount gets a reference to the given int32 and assigns it to the AttemptCount field.
func (o *BillingInvoice) SetAttemptCount(v int32) {
	o.AttemptCount = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *BillingInvoice) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillingInvoice) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *BillingInvoice) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *BillingInvoice) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetCreditApplied returns the CreditApplied field value if set, zero value otherwise.
func (o *BillingInvoice) GetCreditApplied() int32 {
	if o == nil || IsNil(o.CreditApplied) {
		var ret int32
		return ret
	}
	return *o.CreditApplied
}

// GetCreditAppliedOk returns a tuple with the CreditApplied field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillingInvoice) GetCreditAppliedOk() (*int32, bool) {
	if o == nil || IsNil(o.CreditApplied) {
		return nil, false
	}
	return o.CreditApplied, true
}

// HasCreditApplied returns a boolean if a field has been set.
func (o *BillingInvoice) HasCreditApplied() bool {
	if o != nil && !IsNil(o.CreditApplied) {
		return true
	}

	return false
}

// SetCreditApplied gets a reference to the given int32 and assigns it to the CreditApplied field.
func (o *BillingInvoice) SetCreditApplied(v int32) {
	o.CreditApplied = &v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *BillingInvoice) GetCurrency() string {
	if o == nil || IsNil(o.Currency) {
		var ret string
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillingInvoice) GetCurrencyOk() (*string, bool) {
	if o == nil || IsNil(o.Currency) {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *BillingInvoice) HasCurrency() bool {
	if o != nil && !IsNil(o.Currency) {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *BillingInvoice) SetCurrency(v string) {
	o.Currency = &v
}

// GetCustomerEmail returns the CustomerEmail field value if set, zero value otherwise.
func (o *BillingInvoice) GetCustomerEmail() string {
	if o == nil || IsNil(o.CustomerEmail) {
		var ret string
		return ret
	}
	return *o.CustomerEmail
}

// GetCustomerEmailOk returns a tuple with the CustomerEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillingInvoice) GetCustomerEmailOk() (*string, bool) {
	if o == nil || IsNil(o.CustomerEmail) {
		return nil, false
	}
	return o.CustomerEmail, true
}

// HasCustomerEmail returns a boolean if a field has been set.
func (o *BillingInvoice) HasCustomerEmail() bool {
	if o != nil && !IsNil(o.CustomerEmail) {
		return true
	}

	return false
}

// SetCustomerEmail gets a reference to the given string and assigns it to the CustomerEmail field.
func (o *BillingInvoice) SetCustomerEmail(v string) {
	o.CustomerEmail = &v
}

// GetDiscount returns the Discount field value if set, zero value otherwise.
func (o *BillingInvoice) GetDiscount() int32 {
	if o == nil || IsNil(o.Discount) {
		var ret int32
		return ret
	}
	return *o.Discount
}

// GetDiscountOk returns a tuple with the Discount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillingInvoice) GetDiscountOk() (*int32, bool) {
	if o == nil || IsNil(o.Discount) {
		return nil, false
	}
	return o.Discount, true
}

// HasDiscount returns a boolean if a field has been set.
func (o *BillingInvoice) HasDiscount() bool {
	if o != nil && !IsNil(o.Discount) {
		return true
	}

	return false
}

// SetDiscount gets a reference to the given int32 and assigns it to the Discount field.
func (o *BillingInvoice) SetDiscount(v int32) {
	o.Discount = &v
}

// GetDueDate returns the DueDate field value if set, zero value otherwise.
func (o *BillingInvoice) GetDueDate() string {
	if o == nil || IsNil(o.DueDate) {
		var ret string
		return ret
	}
	return *o.DueDate
}

// GetDueDateOk returns a tuple with the DueDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillingInvoice) GetDueDateOk() (*string, bool) {
	if o == nil || IsNil(o.DueDate) {
		return nil, false
	}
	return o.DueDate, true
}

// HasDueDate returns a boolean if a field has been set.
func (o *BillingInvoice) HasDueDate() bool {
	if o != nil && !IsNil(o.DueDate) {
		return true
	}

	return false
}

// SetDueDate gets a reference to the given string and assigns it to the DueDate field.
func (o *BillingInvoice) SetDueDate(v string) {
	o.DueDate = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *BillingInvoice) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillingInvoice) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *BillingInvoice) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *BillingInvoice) SetId(v string) {
	o.Id = &v
}

// GetLineItems returns the LineItems field value if set, zero value otherwise.
func (o *BillingInvoice) GetLineItems() []InvoiceLineItem {
	if o == nil || IsNil(o.LineItems) {
		var ret []InvoiceLineItem
		return ret
	}
	return o.LineItems
}

// GetLineItemsOk returns a tuple with the LineItems field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillingInvoice) GetLineItemsOk() ([]InvoiceLineItem, bool) {
	if o == nil || IsNil(o.LineItems) {
		return nil, false
	}
	return o.LineItems, true
}

// HasLineItems returns a boolean if a field has been set.
func (o *BillingInvoice) HasLineItems() bool {
	if o != nil && !IsNil(o.LineItems) {
		return true
	}

	return false
}

// SetLineItems gets a reference to the given []InvoiceLineItem and assigns it to the LineItems field.
func (o *BillingInvoice) SetLineItems(v []InvoiceLineItem) {
	o.LineItems = v
}

// GetNumber returns the Number field value if set, zero value otherwise.
func (o *BillingInvoice) GetNumber() int32 {
	if o == nil || IsNil(o.Number) {
		var ret int32
		return ret
	}
	return *o.Number
}

// GetNumberOk returns a tuple with the Number field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillingInvoice) GetNumberOk() (*int32, bool) {
	if o == nil || IsNil(o.Number) {
		return nil, false
	}
	return o.Number, true
}

// HasNumber returns a boolean if a field has been set.
func (o *BillingInvoice) HasNumber() bool {
	if o != nil && !IsNil(o.Number) {
		return true
	}

	return false
}

// SetNumber gets a reference to the given int32 and assigns it to the Number field.
func (o *BillingInvoice) SetNumber(v int32) {
	o.Number = &v
}

// GetNumberStr returns the NumberStr field value if set, zero value otherwise.
func (o *BillingInvoice) GetNumberStr() string {
	if o == nil || IsNil(o.NumberStr) {
		var ret string
		return ret
	}
	return *o.NumberStr
}

// GetNumberStrOk returns a tuple with the NumberStr field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillingInvoice) GetNumberStrOk() (*string, bool) {
	if o == nil || IsNil(o.NumberStr) {
		return nil, false
	}
	return o.NumberStr, true
}

// HasNumberStr returns a boolean if a field has been set.
func (o *BillingInvoice) HasNumberStr() bool {
	if o != nil && !IsNil(o.NumberStr) {
		return true
	}

	return false
}

// SetNumberStr gets a reference to the given string and assigns it to the NumberStr field.
func (o *BillingInvoice) SetNumberStr(v string) {
	o.NumberStr = &v
}

// GetPaidAt returns the PaidAt field value if set, zero value otherwise.
func (o *BillingInvoice) GetPaidAt() string {
	if o == nil || IsNil(o.PaidAt) {
		var ret string
		return ret
	}
	return *o.PaidAt
}

// GetPaidAtOk returns a tuple with the PaidAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillingInvoice) GetPaidAtOk() (*string, bool) {
	if o == nil || IsNil(o.PaidAt) {
		return nil, false
	}
	return o.PaidAt, true
}

// HasPaidAt returns a boolean if a field has been set.
func (o *BillingInvoice) HasPaidAt() bool {
	if o != nil && !IsNil(o.PaidAt) {
		return true
	}

	return false
}

// SetPaidAt gets a reference to the given string and assigns it to the PaidAt field.
func (o *BillingInvoice) SetPaidAt(v string) {
	o.PaidAt = &v
}

// GetPaymentMethod returns the PaymentMethod field value if set, zero value otherwise.
func (o *BillingInvoice) GetPaymentMethod() string {
	if o == nil || IsNil(o.PaymentMethod) {
		var ret string
		return ret
	}
	return *o.PaymentMethod
}

// GetPaymentMethodOk returns a tuple with the PaymentMethod field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillingInvoice) GetPaymentMethodOk() (*string, bool) {
	if o == nil || IsNil(o.PaymentMethod) {
		return nil, false
	}
	return o.PaymentMethod, true
}

// HasPaymentMethod returns a boolean if a field has been set.
func (o *BillingInvoice) HasPaymentMethod() bool {
	if o != nil && !IsNil(o.PaymentMethod) {
		return true
	}

	return false
}

// SetPaymentMethod gets a reference to the given string and assigns it to the PaymentMethod field.
func (o *BillingInvoice) SetPaymentMethod(v string) {
	o.PaymentMethod = &v
}

// GetPaymentRef returns the PaymentRef field value if set, zero value otherwise.
func (o *BillingInvoice) GetPaymentRef() string {
	if o == nil || IsNil(o.PaymentRef) {
		var ret string
		return ret
	}
	return *o.PaymentRef
}

// GetPaymentRefOk returns a tuple with the PaymentRef field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillingInvoice) GetPaymentRefOk() (*string, bool) {
	if o == nil || IsNil(o.PaymentRef) {
		return nil, false
	}
	return o.PaymentRef, true
}

// HasPaymentRef returns a boolean if a field has been set.
func (o *BillingInvoice) HasPaymentRef() bool {
	if o != nil && !IsNil(o.PaymentRef) {
		return true
	}

	return false
}

// SetPaymentRef gets a reference to the given string and assigns it to the PaymentRef field.
func (o *BillingInvoice) SetPaymentRef(v string) {
	o.PaymentRef = &v
}

// GetPeriodEnd returns the PeriodEnd field value if set, zero value otherwise.
func (o *BillingInvoice) GetPeriodEnd() string {
	if o == nil || IsNil(o.PeriodEnd) {
		var ret string
		return ret
	}
	return *o.PeriodEnd
}

// GetPeriodEndOk returns a tuple with the PeriodEnd field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillingInvoice) GetPeriodEndOk() (*string, bool) {
	if o == nil || IsNil(o.PeriodEnd) {
		return nil, false
	}
	return o.PeriodEnd, true
}

// HasPeriodEnd returns a boolean if a field has been set.
func (o *BillingInvoice) HasPeriodEnd() bool {
	if o != nil && !IsNil(o.PeriodEnd) {
		return true
	}

	return false
}

// SetPeriodEnd gets a reference to the given string and assigns it to the PeriodEnd field.
func (o *BillingInvoice) SetPeriodEnd(v string) {
	o.PeriodEnd = &v
}

// GetPeriodStart returns the PeriodStart field value if set, zero value otherwise.
func (o *BillingInvoice) GetPeriodStart() string {
	if o == nil || IsNil(o.PeriodStart) {
		var ret string
		return ret
	}
	return *o.PeriodStart
}

// GetPeriodStartOk returns a tuple with the PeriodStart field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillingInvoice) GetPeriodStartOk() (*string, bool) {
	if o == nil || IsNil(o.PeriodStart) {
		return nil, false
	}
	return o.PeriodStart, true
}

// HasPeriodStart returns a boolean if a field has been set.
func (o *BillingInvoice) HasPeriodStart() bool {
	if o != nil && !IsNil(o.PeriodStart) {
		return true
	}

	return false
}

// SetPeriodStart gets a reference to the given string and assigns it to the PeriodStart field.
func (o *BillingInvoice) SetPeriodStart(v string) {
	o.PeriodStart = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *BillingInvoice) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillingInvoice) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *BillingInvoice) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *BillingInvoice) SetStatus(v string) {
	o.Status = &v
}

// GetSubscriptionId returns the SubscriptionId field value if set, zero value otherwise.
func (o *BillingInvoice) GetSubscriptionId() string {
	if o == nil || IsNil(o.SubscriptionId) {
		var ret string
		return ret
	}
	return *o.SubscriptionId
}

// GetSubscriptionIdOk returns a tuple with the SubscriptionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillingInvoice) GetSubscriptionIdOk() (*string, bool) {
	if o == nil || IsNil(o.SubscriptionId) {
		return nil, false
	}
	return o.SubscriptionId, true
}

// HasSubscriptionId returns a boolean if a field has been set.
func (o *BillingInvoice) HasSubscriptionId() bool {
	if o != nil && !IsNil(o.SubscriptionId) {
		return true
	}

	return false
}

// SetSubscriptionId gets a reference to the given string and assigns it to the SubscriptionId field.
func (o *BillingInvoice) SetSubscriptionId(v string) {
	o.SubscriptionId = &v
}

// GetSubtotal returns the Subtotal field value if set, zero value otherwise.
func (o *BillingInvoice) GetSubtotal() int32 {
	if o == nil || IsNil(o.Subtotal) {
		var ret int32
		return ret
	}
	return *o.Subtotal
}

// GetSubtotalOk returns a tuple with the Subtotal field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillingInvoice) GetSubtotalOk() (*int32, bool) {
	if o == nil || IsNil(o.Subtotal) {
		return nil, false
	}
	return o.Subtotal, true
}

// HasSubtotal returns a boolean if a field has been set.
func (o *BillingInvoice) HasSubtotal() bool {
	if o != nil && !IsNil(o.Subtotal) {
		return true
	}

	return false
}

// SetSubtotal gets a reference to the given int32 and assigns it to the Subtotal field.
func (o *BillingInvoice) SetSubtotal(v int32) {
	o.Subtotal = &v
}

// GetTax returns the Tax field value if set, zero value otherwise.
func (o *BillingInvoice) GetTax() int32 {
	if o == nil || IsNil(o.Tax) {
		var ret int32
		return ret
	}
	return *o.Tax
}

// GetTaxOk returns a tuple with the Tax field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillingInvoice) GetTaxOk() (*int32, bool) {
	if o == nil || IsNil(o.Tax) {
		return nil, false
	}
	return o.Tax, true
}

// HasTax returns a boolean if a field has been set.
func (o *BillingInvoice) HasTax() bool {
	if o != nil && !IsNil(o.Tax) {
		return true
	}

	return false
}

// SetTax gets a reference to the given int32 and assigns it to the Tax field.
func (o *BillingInvoice) SetTax(v int32) {
	o.Tax = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *BillingInvoice) GetUpdatedAt() string {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret string
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillingInvoice) GetUpdatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *BillingInvoice) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given string and assigns it to the UpdatedAt field.
func (o *BillingInvoice) SetUpdatedAt(v string) {
	o.UpdatedAt = &v
}

// GetUserId returns the UserId field value if set, zero value otherwise.
func (o *BillingInvoice) GetUserId() string {
	if o == nil || IsNil(o.UserId) {
		var ret string
		return ret
	}
	return *o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillingInvoice) GetUserIdOk() (*string, bool) {
	if o == nil || IsNil(o.UserId) {
		return nil, false
	}
	return o.UserId, true
}

// HasUserId returns a boolean if a field has been set.
func (o *BillingInvoice) HasUserId() bool {
	if o != nil && !IsNil(o.UserId) {
		return true
	}

	return false
}

// SetUserId gets a reference to the given string and assigns it to the UserId field.
func (o *BillingInvoice) SetUserId(v string) {
	o.UserId = &v
}

// GetVoidedAt returns the VoidedAt field value if set, zero value otherwise.
func (o *BillingInvoice) GetVoidedAt() string {
	if o == nil || IsNil(o.VoidedAt) {
		var ret string
		return ret
	}
	return *o.VoidedAt
}

// GetVoidedAtOk returns a tuple with the VoidedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillingInvoice) GetVoidedAtOk() (*string, bool) {
	if o == nil || IsNil(o.VoidedAt) {
		return nil, false
	}
	return o.VoidedAt, true
}

// HasVoidedAt returns a boolean if a field has been set.
func (o *BillingInvoice) HasVoidedAt() bool {
	if o != nil && !IsNil(o.VoidedAt) {
		return true
	}

	return false
}

// SetVoidedAt gets a reference to the given string and assigns it to the VoidedAt field.
func (o *BillingInvoice) SetVoidedAt(v string) {
	o.VoidedAt = &v
}

func (o BillingInvoice) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BillingInvoice) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AmountDue) {
		toSerialize["amountDue"] = o.AmountDue
	}
	if !IsNil(o.AmountPaid) {
		toSerialize["amountPaid"] = o.AmountPaid
	}
	if !IsNil(o.AttemptCount) {
		toSerialize["attemptCount"] = o.AttemptCount
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if !IsNil(o.CreditApplied) {
		toSerialize["creditApplied"] = o.CreditApplied
	}
	if !IsNil(o.Currency) {
		toSerialize["currency"] = o.Currency
	}
	if !IsNil(o.CustomerEmail) {
		toSerialize["customerEmail"] = o.CustomerEmail
	}
	if !IsNil(o.Discount) {
		toSerialize["discount"] = o.Discount
	}
	if !IsNil(o.DueDate) {
		toSerialize["dueDate"] = o.DueDate
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.LineItems) {
		toSerialize["lineItems"] = o.LineItems
	}
	if !IsNil(o.Number) {
		toSerialize["number"] = o.Number
	}
	if !IsNil(o.NumberStr) {
		toSerialize["numberStr"] = o.NumberStr
	}
	if !IsNil(o.PaidAt) {
		toSerialize["paidAt"] = o.PaidAt
	}
	if !IsNil(o.PaymentMethod) {
		toSerialize["paymentMethod"] = o.PaymentMethod
	}
	if !IsNil(o.PaymentRef) {
		toSerialize["paymentRef"] = o.PaymentRef
	}
	if !IsNil(o.PeriodEnd) {
		toSerialize["periodEnd"] = o.PeriodEnd
	}
	if !IsNil(o.PeriodStart) {
		toSerialize["periodStart"] = o.PeriodStart
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.SubscriptionId) {
		toSerialize["subscriptionId"] = o.SubscriptionId
	}
	if !IsNil(o.Subtotal) {
		toSerialize["subtotal"] = o.Subtotal
	}
	if !IsNil(o.Tax) {
		toSerialize["tax"] = o.Tax
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updatedAt"] = o.UpdatedAt
	}
	if !IsNil(o.UserId) {
		toSerialize["userId"] = o.UserId
	}
	if !IsNil(o.VoidedAt) {
		toSerialize["voidedAt"] = o.VoidedAt
	}
	return toSerialize, nil
}

type NullableBillingInvoice struct {
	value *BillingInvoice
	isSet bool
}

func (v NullableBillingInvoice) Get() *BillingInvoice {
	return v.value
}

func (v *NullableBillingInvoice) Set(val *BillingInvoice) {
	v.value = val
	v.isSet = true
}

func (v NullableBillingInvoice) IsSet() bool {
	return v.isSet
}

func (v *NullableBillingInvoice) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBillingInvoice(val *BillingInvoice) *NullableBillingInvoice {
	return &NullableBillingInvoice{value: val, isSet: true}
}

func (v NullableBillingInvoice) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBillingInvoice) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
