/*
Hanzo Cloud — Unified API (V8 · Open Edition)

The single unified OpenAPI surface for ALL Hanzo services, aggregated from the per-service specs. Every route is https://api.hanzo.ai/v1/<service>/_*. Grouped by the canonical domains in capabilities.yaml (the ONE registry). cloud/openapi.yaml is hanzoai/cloud's own woven document, copied verbatim by sync.py, and it wins wherever it and a hand-written spec describe the same route. Regenerated by merge.py — edit the per-service <svc>/openapi.yaml + capabilities.yaml, not this file.

API version: 8.0.0
Contact: support@hanzo.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hanzoai

import (
	"encoding/json"
)

// checks if the CloudSaaSPlan type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CloudSaaSPlan{}

// CloudSaaSPlan struct for CloudSaaSPlan
type CloudSaaSPlan struct {
	Active   *int32  `json:"active,omitempty"`
	Category *string `json:"category,omitempty"`
	MrrCents *int32  `json:"mrrCents,omitempty"`
	Name     *string `json:"name,omitempty"`
	Plan     *string `json:"plan,omitempty"`
	Seats    *int32  `json:"seats,omitempty"`
	Trialing *int32  `json:"trialing,omitempty"`
}

// NewCloudSaaSPlan instantiates a new CloudSaaSPlan object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCloudSaaSPlan() *CloudSaaSPlan {
	this := CloudSaaSPlan{}
	return &this
}

// NewCloudSaaSPlanWithDefaults instantiates a new CloudSaaSPlan object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCloudSaaSPlanWithDefaults() *CloudSaaSPlan {
	this := CloudSaaSPlan{}
	return &this
}

// GetActive returns the Active field value if set, zero value otherwise.
func (o *CloudSaaSPlan) GetActive() int32 {
	if o == nil || IsNil(o.Active) {
		var ret int32
		return ret
	}
	return *o.Active
}

// GetActiveOk returns a tuple with the Active field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudSaaSPlan) GetActiveOk() (*int32, bool) {
	if o == nil || IsNil(o.Active) {
		return nil, false
	}
	return o.Active, true
}

// HasActive returns a boolean if a field has been set.
func (o *CloudSaaSPlan) HasActive() bool {
	if o != nil && !IsNil(o.Active) {
		return true
	}

	return false
}

// SetActive gets a reference to the given int32 and assigns it to the Active field.
func (o *CloudSaaSPlan) SetActive(v int32) {
	o.Active = &v
}

// GetCategory returns the Category field value if set, zero value otherwise.
func (o *CloudSaaSPlan) GetCategory() string {
	if o == nil || IsNil(o.Category) {
		var ret string
		return ret
	}
	return *o.Category
}

// GetCategoryOk returns a tuple with the Category field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudSaaSPlan) GetCategoryOk() (*string, bool) {
	if o == nil || IsNil(o.Category) {
		return nil, false
	}
	return o.Category, true
}

// HasCategory returns a boolean if a field has been set.
func (o *CloudSaaSPlan) HasCategory() bool {
	if o != nil && !IsNil(o.Category) {
		return true
	}

	return false
}

// SetCategory gets a reference to the given string and assigns it to the Category field.
func (o *CloudSaaSPlan) SetCategory(v string) {
	o.Category = &v
}

// GetMrrCents returns the MrrCents field value if set, zero value otherwise.
func (o *CloudSaaSPlan) GetMrrCents() int32 {
	if o == nil || IsNil(o.MrrCents) {
		var ret int32
		return ret
	}
	return *o.MrrCents
}

// GetMrrCentsOk returns a tuple with the MrrCents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudSaaSPlan) GetMrrCentsOk() (*int32, bool) {
	if o == nil || IsNil(o.MrrCents) {
		return nil, false
	}
	return o.MrrCents, true
}

// HasMrrCents returns a boolean if a field has been set.
func (o *CloudSaaSPlan) HasMrrCents() bool {
	if o != nil && !IsNil(o.MrrCents) {
		return true
	}

	return false
}

// SetMrrCents gets a reference to the given int32 and assigns it to the MrrCents field.
func (o *CloudSaaSPlan) SetMrrCents(v int32) {
	o.MrrCents = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CloudSaaSPlan) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudSaaSPlan) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CloudSaaSPlan) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CloudSaaSPlan) SetName(v string) {
	o.Name = &v
}

// GetPlan returns the Plan field value if set, zero value otherwise.
func (o *CloudSaaSPlan) GetPlan() string {
	if o == nil || IsNil(o.Plan) {
		var ret string
		return ret
	}
	return *o.Plan
}

// GetPlanOk returns a tuple with the Plan field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudSaaSPlan) GetPlanOk() (*string, bool) {
	if o == nil || IsNil(o.Plan) {
		return nil, false
	}
	return o.Plan, true
}

// HasPlan returns a boolean if a field has been set.
func (o *CloudSaaSPlan) HasPlan() bool {
	if o != nil && !IsNil(o.Plan) {
		return true
	}

	return false
}

// SetPlan gets a reference to the given string and assigns it to the Plan field.
func (o *CloudSaaSPlan) SetPlan(v string) {
	o.Plan = &v
}

// GetSeats returns the Seats field value if set, zero value otherwise.
func (o *CloudSaaSPlan) GetSeats() int32 {
	if o == nil || IsNil(o.Seats) {
		var ret int32
		return ret
	}
	return *o.Seats
}

// GetSeatsOk returns a tuple with the Seats field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudSaaSPlan) GetSeatsOk() (*int32, bool) {
	if o == nil || IsNil(o.Seats) {
		return nil, false
	}
	return o.Seats, true
}

// HasSeats returns a boolean if a field has been set.
func (o *CloudSaaSPlan) HasSeats() bool {
	if o != nil && !IsNil(o.Seats) {
		return true
	}

	return false
}

// SetSeats gets a reference to the given int32 and assigns it to the Seats field.
func (o *CloudSaaSPlan) SetSeats(v int32) {
	o.Seats = &v
}

// GetTrialing returns the Trialing field value if set, zero value otherwise.
func (o *CloudSaaSPlan) GetTrialing() int32 {
	if o == nil || IsNil(o.Trialing) {
		var ret int32
		return ret
	}
	return *o.Trialing
}

// GetTrialingOk returns a tuple with the Trialing field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudSaaSPlan) GetTrialingOk() (*int32, bool) {
	if o == nil || IsNil(o.Trialing) {
		return nil, false
	}
	return o.Trialing, true
}

// HasTrialing returns a boolean if a field has been set.
func (o *CloudSaaSPlan) HasTrialing() bool {
	if o != nil && !IsNil(o.Trialing) {
		return true
	}

	return false
}

// SetTrialing gets a reference to the given int32 and assigns it to the Trialing field.
func (o *CloudSaaSPlan) SetTrialing(v int32) {
	o.Trialing = &v
}

func (o CloudSaaSPlan) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CloudSaaSPlan) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Active) {
		toSerialize["active"] = o.Active
	}
	if !IsNil(o.Category) {
		toSerialize["category"] = o.Category
	}
	if !IsNil(o.MrrCents) {
		toSerialize["mrrCents"] = o.MrrCents
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Plan) {
		toSerialize["plan"] = o.Plan
	}
	if !IsNil(o.Seats) {
		toSerialize["seats"] = o.Seats
	}
	if !IsNil(o.Trialing) {
		toSerialize["trialing"] = o.Trialing
	}
	return toSerialize, nil
}

type NullableCloudSaaSPlan struct {
	value *CloudSaaSPlan
	isSet bool
}

func (v NullableCloudSaaSPlan) Get() *CloudSaaSPlan {
	return v.value
}

func (v *NullableCloudSaaSPlan) Set(val *CloudSaaSPlan) {
	v.value = val
	v.isSet = true
}

func (v NullableCloudSaaSPlan) IsSet() bool {
	return v.isSet
}

func (v *NullableCloudSaaSPlan) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCloudSaaSPlan(val *CloudSaaSPlan) *NullableCloudSaaSPlan {
	return &NullableCloudSaaSPlan{value: val, isSet: true}
}

func (v NullableCloudSaaSPlan) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCloudSaaSPlan) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
