/*
Hanzo Cloud — Unified API (V8 · Open Edition)

The single unified OpenAPI surface for ALL Hanzo services, aggregated from the per-service specs. Every route is https://api.hanzo.ai/v1/<service>/_*. Grouped by the canonical domains in capabilities.yaml (the ONE registry). cloud/openapi.yaml is hanzoai/cloud's own woven document, copied verbatim by sync.py, and it wins wherever it and a hand-written spec describe the same route. Regenerated by merge.py — edit the per-service <svc>/openapi.yaml + capabilities.yaml, not this file.

API version: 8.0.0
Contact: support@hanzo.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hanzoai

import (
	"encoding/json"
)

// checks if the CloudValidatorList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CloudValidatorList{}

// CloudValidatorList struct for CloudValidatorList
type CloudValidatorList struct {
	// Data is one entry per slot this org has claimed.
	Data []CloudSlotView `json:"data,omitempty"`
	// Network is the luxd network slug new nodes join on this deployment.
	Network *string `json:"network,omitempty"`
}

// NewCloudValidatorList instantiates a new CloudValidatorList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCloudValidatorList() *CloudValidatorList {
	this := CloudValidatorList{}
	return &this
}

// NewCloudValidatorListWithDefaults instantiates a new CloudValidatorList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCloudValidatorListWithDefaults() *CloudValidatorList {
	this := CloudValidatorList{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *CloudValidatorList) GetData() []CloudSlotView {
	if o == nil || IsNil(o.Data) {
		var ret []CloudSlotView
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudValidatorList) GetDataOk() ([]CloudSlotView, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *CloudValidatorList) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []CloudSlotView and assigns it to the Data field.
func (o *CloudValidatorList) SetData(v []CloudSlotView) {
	o.Data = v
}

// GetNetwork returns the Network field value if set, zero value otherwise.
func (o *CloudValidatorList) GetNetwork() string {
	if o == nil || IsNil(o.Network) {
		var ret string
		return ret
	}
	return *o.Network
}

// GetNetworkOk returns a tuple with the Network field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudValidatorList) GetNetworkOk() (*string, bool) {
	if o == nil || IsNil(o.Network) {
		return nil, false
	}
	return o.Network, true
}

// HasNetwork returns a boolean if a field has been set.
func (o *CloudValidatorList) HasNetwork() bool {
	if o != nil && !IsNil(o.Network) {
		return true
	}

	return false
}

// SetNetwork gets a reference to the given string and assigns it to the Network field.
func (o *CloudValidatorList) SetNetwork(v string) {
	o.Network = &v
}

func (o CloudValidatorList) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CloudValidatorList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Network) {
		toSerialize["network"] = o.Network
	}
	return toSerialize, nil
}

type NullableCloudValidatorList struct {
	value *CloudValidatorList
	isSet bool
}

func (v NullableCloudValidatorList) Get() *CloudValidatorList {
	return v.value
}

func (v *NullableCloudValidatorList) Set(val *CloudValidatorList) {
	v.value = val
	v.isSet = true
}

func (v NullableCloudValidatorList) IsSet() bool {
	return v.isSet
}

func (v *NullableCloudValidatorList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCloudValidatorList(val *CloudValidatorList) *NullableCloudValidatorList {
	return &NullableCloudValidatorList{value: val, isSet: true}
}

func (v NullableCloudValidatorList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCloudValidatorList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
