/*
Hanzo Cloud — Unified API (V8 · Open Edition)

The single unified OpenAPI surface for ALL Hanzo services, aggregated from the per-service specs. Every route is https://api.hanzo.ai/v1/<service>/_*. Grouped by the canonical domains in capabilities.yaml (the ONE registry). cloud/openapi.yaml is hanzoai/cloud's own woven document, copied verbatim by sync.py, and it wins wherever it and a hand-written spec describe the same route. Regenerated by merge.py — edit the per-service <svc>/openapi.yaml + capabilities.yaml, not this file.

API version: 8.0.0
Contact: support@hanzo.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hanzoai

import (
	"encoding/json"
)

// checks if the CloudBlueprintIndex type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CloudBlueprintIndex{}

// CloudBlueprintIndex struct for CloudBlueprintIndex
type CloudBlueprintIndex struct {
	// Data is one row per embedded blueprint, sorted by template id.
	Data []CloudBlueprintRow `json:"data,omitempty"`
}

// NewCloudBlueprintIndex instantiates a new CloudBlueprintIndex object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCloudBlueprintIndex() *CloudBlueprintIndex {
	this := CloudBlueprintIndex{}
	return &this
}

// NewCloudBlueprintIndexWithDefaults instantiates a new CloudBlueprintIndex object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCloudBlueprintIndexWithDefaults() *CloudBlueprintIndex {
	this := CloudBlueprintIndex{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *CloudBlueprintIndex) GetData() []CloudBlueprintRow {
	if o == nil || IsNil(o.Data) {
		var ret []CloudBlueprintRow
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudBlueprintIndex) GetDataOk() ([]CloudBlueprintRow, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *CloudBlueprintIndex) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []CloudBlueprintRow and assigns it to the Data field.
func (o *CloudBlueprintIndex) SetData(v []CloudBlueprintRow) {
	o.Data = v
}

func (o CloudBlueprintIndex) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CloudBlueprintIndex) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableCloudBlueprintIndex struct {
	value *CloudBlueprintIndex
	isSet bool
}

func (v NullableCloudBlueprintIndex) Get() *CloudBlueprintIndex {
	return v.value
}

func (v *NullableCloudBlueprintIndex) Set(val *CloudBlueprintIndex) {
	v.value = val
	v.isSet = true
}

func (v NullableCloudBlueprintIndex) IsSet() bool {
	return v.isSet
}

func (v *NullableCloudBlueprintIndex) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCloudBlueprintIndex(val *CloudBlueprintIndex) *NullableCloudBlueprintIndex {
	return &NullableCloudBlueprintIndex{value: val, isSet: true}
}

func (v NullableCloudBlueprintIndex) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCloudBlueprintIndex) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
