/*
Hanzo Cloud — Unified API (V8 · Open Edition)

The single unified OpenAPI surface for ALL Hanzo services, aggregated from the per-service specs. Every route is https://api.hanzo.ai/v1/<service>/_*. Grouped by the canonical domains in capabilities.yaml (the ONE registry). Regenerated by merge.py — edit the per-service <svc>/openapi.yaml + capabilities.yaml, not this file.

API version: 8.0.0
Contact: support@hanzo.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hanzoai

import (
	"encoding/json"
)

// checks if the AdminFinanceDerived type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdminFinanceDerived{}

// AdminFinanceDerived struct for AdminFinanceDerived
type AdminFinanceDerived struct {
	GrossMarginCents *int64   `json:"grossMarginCents,omitempty"`
	GrossMarginPct   *float64 `json:"grossMarginPct,omitempty"`
	RunwayDays       *float64 `json:"runwayDays,omitempty"`
	Profitable       *bool    `json:"profitable,omitempty"`
}

// NewAdminFinanceDerived instantiates a new AdminFinanceDerived object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdminFinanceDerived() *AdminFinanceDerived {
	this := AdminFinanceDerived{}
	return &this
}

// NewAdminFinanceDerivedWithDefaults instantiates a new AdminFinanceDerived object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdminFinanceDerivedWithDefaults() *AdminFinanceDerived {
	this := AdminFinanceDerived{}
	return &this
}

// GetGrossMarginCents returns the GrossMarginCents field value if set, zero value otherwise.
func (o *AdminFinanceDerived) GetGrossMarginCents() int64 {
	if o == nil || IsNil(o.GrossMarginCents) {
		var ret int64
		return ret
	}
	return *o.GrossMarginCents
}

// GetGrossMarginCentsOk returns a tuple with the GrossMarginCents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminFinanceDerived) GetGrossMarginCentsOk() (*int64, bool) {
	if o == nil || IsNil(o.GrossMarginCents) {
		return nil, false
	}
	return o.GrossMarginCents, true
}

// HasGrossMarginCents returns a boolean if a field has been set.
func (o *AdminFinanceDerived) HasGrossMarginCents() bool {
	if o != nil && !IsNil(o.GrossMarginCents) {
		return true
	}

	return false
}

// SetGrossMarginCents gets a reference to the given int64 and assigns it to the GrossMarginCents field.
func (o *AdminFinanceDerived) SetGrossMarginCents(v int64) {
	o.GrossMarginCents = &v
}

// GetGrossMarginPct returns the GrossMarginPct field value if set, zero value otherwise.
func (o *AdminFinanceDerived) GetGrossMarginPct() float64 {
	if o == nil || IsNil(o.GrossMarginPct) {
		var ret float64
		return ret
	}
	return *o.GrossMarginPct
}

// GetGrossMarginPctOk returns a tuple with the GrossMarginPct field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminFinanceDerived) GetGrossMarginPctOk() (*float64, bool) {
	if o == nil || IsNil(o.GrossMarginPct) {
		return nil, false
	}
	return o.GrossMarginPct, true
}

// HasGrossMarginPct returns a boolean if a field has been set.
func (o *AdminFinanceDerived) HasGrossMarginPct() bool {
	if o != nil && !IsNil(o.GrossMarginPct) {
		return true
	}

	return false
}

// SetGrossMarginPct gets a reference to the given float64 and assigns it to the GrossMarginPct field.
func (o *AdminFinanceDerived) SetGrossMarginPct(v float64) {
	o.GrossMarginPct = &v
}

// GetRunwayDays returns the RunwayDays field value if set, zero value otherwise.
func (o *AdminFinanceDerived) GetRunwayDays() float64 {
	if o == nil || IsNil(o.RunwayDays) {
		var ret float64
		return ret
	}
	return *o.RunwayDays
}

// GetRunwayDaysOk returns a tuple with the RunwayDays field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminFinanceDerived) GetRunwayDaysOk() (*float64, bool) {
	if o == nil || IsNil(o.RunwayDays) {
		return nil, false
	}
	return o.RunwayDays, true
}

// HasRunwayDays returns a boolean if a field has been set.
func (o *AdminFinanceDerived) HasRunwayDays() bool {
	if o != nil && !IsNil(o.RunwayDays) {
		return true
	}

	return false
}

// SetRunwayDays gets a reference to the given float64 and assigns it to the RunwayDays field.
func (o *AdminFinanceDerived) SetRunwayDays(v float64) {
	o.RunwayDays = &v
}

// GetProfitable returns the Profitable field value if set, zero value otherwise.
func (o *AdminFinanceDerived) GetProfitable() bool {
	if o == nil || IsNil(o.Profitable) {
		var ret bool
		return ret
	}
	return *o.Profitable
}

// GetProfitableOk returns a tuple with the Profitable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminFinanceDerived) GetProfitableOk() (*bool, bool) {
	if o == nil || IsNil(o.Profitable) {
		return nil, false
	}
	return o.Profitable, true
}

// HasProfitable returns a boolean if a field has been set.
func (o *AdminFinanceDerived) HasProfitable() bool {
	if o != nil && !IsNil(o.Profitable) {
		return true
	}

	return false
}

// SetProfitable gets a reference to the given bool and assigns it to the Profitable field.
func (o *AdminFinanceDerived) SetProfitable(v bool) {
	o.Profitable = &v
}

func (o AdminFinanceDerived) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdminFinanceDerived) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.GrossMarginCents) {
		toSerialize["grossMarginCents"] = o.GrossMarginCents
	}
	if !IsNil(o.GrossMarginPct) {
		toSerialize["grossMarginPct"] = o.GrossMarginPct
	}
	if !IsNil(o.RunwayDays) {
		toSerialize["runwayDays"] = o.RunwayDays
	}
	if !IsNil(o.Profitable) {
		toSerialize["profitable"] = o.Profitable
	}
	return toSerialize, nil
}

type NullableAdminFinanceDerived struct {
	value *AdminFinanceDerived
	isSet bool
}

func (v NullableAdminFinanceDerived) Get() *AdminFinanceDerived {
	return v.value
}

func (v *NullableAdminFinanceDerived) Set(val *AdminFinanceDerived) {
	v.value = val
	v.isSet = true
}

func (v NullableAdminFinanceDerived) IsSet() bool {
	return v.isSet
}

func (v *NullableAdminFinanceDerived) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdminFinanceDerived(val *AdminFinanceDerived) *NullableAdminFinanceDerived {
	return &NullableAdminFinanceDerived{value: val, isSet: true}
}

func (v NullableAdminFinanceDerived) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdminFinanceDerived) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
