/*
Hanzo Cloud API

Composed from each subsystem's own projection of its router, in the fleet's mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hanzoai

import (
	"encoding/json"
)

// checks if the ReferralsOut type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReferralsOut{}

// ReferralsOut struct for ReferralsOut
type ReferralsOut struct {
	// Data is the referral board: leaders, funnel, tally and per-level liability.
	Data   *ReferralBoard `json:"data,omitempty"`
	Msg    *string        `json:"msg,omitempty"`
	Status *string        `json:"status,omitempty"`
}

// NewReferralsOut instantiates a new ReferralsOut object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReferralsOut() *ReferralsOut {
	this := ReferralsOut{}
	return &this
}

// NewReferralsOutWithDefaults instantiates a new ReferralsOut object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReferralsOutWithDefaults() *ReferralsOut {
	this := ReferralsOut{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ReferralsOut) GetData() ReferralBoard {
	if o == nil || IsNil(o.Data) {
		var ret ReferralBoard
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReferralsOut) GetDataOk() (*ReferralBoard, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ReferralsOut) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given ReferralBoard and assigns it to the Data field.
func (o *ReferralsOut) SetData(v ReferralBoard) {
	o.Data = &v
}

// GetMsg returns the Msg field value if set, zero value otherwise.
func (o *ReferralsOut) GetMsg() string {
	if o == nil || IsNil(o.Msg) {
		var ret string
		return ret
	}
	return *o.Msg
}

// GetMsgOk returns a tuple with the Msg field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReferralsOut) GetMsgOk() (*string, bool) {
	if o == nil || IsNil(o.Msg) {
		return nil, false
	}
	return o.Msg, true
}

// HasMsg returns a boolean if a field has been set.
func (o *ReferralsOut) HasMsg() bool {
	if o != nil && !IsNil(o.Msg) {
		return true
	}

	return false
}

// SetMsg gets a reference to the given string and assigns it to the Msg field.
func (o *ReferralsOut) SetMsg(v string) {
	o.Msg = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ReferralsOut) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReferralsOut) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ReferralsOut) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *ReferralsOut) SetStatus(v string) {
	o.Status = &v
}

func (o ReferralsOut) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReferralsOut) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Msg) {
		toSerialize["msg"] = o.Msg
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableReferralsOut struct {
	value *ReferralsOut
	isSet bool
}

func (v NullableReferralsOut) Get() *ReferralsOut {
	return v.value
}

func (v *NullableReferralsOut) Set(val *ReferralsOut) {
	v.value = val
	v.isSet = true
}

func (v NullableReferralsOut) IsSet() bool {
	return v.isSet
}

func (v *NullableReferralsOut) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReferralsOut(val *ReferralsOut) *NullableReferralsOut {
	return &NullableReferralsOut{value: val, isSet: true}
}

func (v NullableReferralsOut) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReferralsOut) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
