/*
Hanzo Cloud — Unified API

The single unified OpenAPI surface for ALL Hanzo services, aggregated from the per-service specs. Every route is https://api.hanzo.ai/v1/<service>/_*. Regenerated by merge.py — edit the per-service <svc>/openapi.yaml, not this file.

API version: 1.0.0
Contact: support@hanzo.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hanzoai

import (
	"encoding/json"
)

// checks if the ConsoleListOrganizationMemberships200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConsoleListOrganizationMemberships200Response{}

// ConsoleListOrganizationMemberships200Response struct for ConsoleListOrganizationMemberships200Response
type ConsoleListOrganizationMemberships200Response struct {
	Memberships []ConsoleMembership `json:"memberships,omitempty"`
}

// NewConsoleListOrganizationMemberships200Response instantiates a new ConsoleListOrganizationMemberships200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConsoleListOrganizationMemberships200Response() *ConsoleListOrganizationMemberships200Response {
	this := ConsoleListOrganizationMemberships200Response{}
	return &this
}

// NewConsoleListOrganizationMemberships200ResponseWithDefaults instantiates a new ConsoleListOrganizationMemberships200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConsoleListOrganizationMemberships200ResponseWithDefaults() *ConsoleListOrganizationMemberships200Response {
	this := ConsoleListOrganizationMemberships200Response{}
	return &this
}

// GetMemberships returns the Memberships field value if set, zero value otherwise.
func (o *ConsoleListOrganizationMemberships200Response) GetMemberships() []ConsoleMembership {
	if o == nil || IsNil(o.Memberships) {
		var ret []ConsoleMembership
		return ret
	}
	return o.Memberships
}

// GetMembershipsOk returns a tuple with the Memberships field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConsoleListOrganizationMemberships200Response) GetMembershipsOk() ([]ConsoleMembership, bool) {
	if o == nil || IsNil(o.Memberships) {
		return nil, false
	}
	return o.Memberships, true
}

// HasMemberships returns a boolean if a field has been set.
func (o *ConsoleListOrganizationMemberships200Response) HasMemberships() bool {
	if o != nil && !IsNil(o.Memberships) {
		return true
	}

	return false
}

// SetMemberships gets a reference to the given []ConsoleMembership and assigns it to the Memberships field.
func (o *ConsoleListOrganizationMemberships200Response) SetMemberships(v []ConsoleMembership) {
	o.Memberships = v
}

func (o ConsoleListOrganizationMemberships200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConsoleListOrganizationMemberships200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Memberships) {
		toSerialize["memberships"] = o.Memberships
	}
	return toSerialize, nil
}

type NullableConsoleListOrganizationMemberships200Response struct {
	value *ConsoleListOrganizationMemberships200Response
	isSet bool
}

func (v NullableConsoleListOrganizationMemberships200Response) Get() *ConsoleListOrganizationMemberships200Response {
	return v.value
}

func (v *NullableConsoleListOrganizationMemberships200Response) Set(val *ConsoleListOrganizationMemberships200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableConsoleListOrganizationMemberships200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableConsoleListOrganizationMemberships200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConsoleListOrganizationMemberships200Response(val *ConsoleListOrganizationMemberships200Response) *NullableConsoleListOrganizationMemberships200Response {
	return &NullableConsoleListOrganizationMemberships200Response{value: val, isSet: true}
}

func (v NullableConsoleListOrganizationMemberships200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConsoleListOrganizationMemberships200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
