/*
Hanzo Cloud — Unified API (V8 · Open Edition)

The single unified OpenAPI surface for ALL Hanzo services, aggregated from the per-service specs. Every route is https://api.hanzo.ai/v1/<service>/_*. Grouped by the canonical domains in capabilities.yaml (the ONE registry). Regenerated by merge.py — edit the per-service <svc>/openapi.yaml + capabilities.yaml, not this file.

API version: 8.0.0
Contact: support@hanzo.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hanzoai

import (
	"encoding/json"
)

// checks if the PricingBlockStoragePricing type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PricingBlockStoragePricing{}

// PricingBlockStoragePricing struct for PricingBlockStoragePricing
type PricingBlockStoragePricing struct {
	PricePerGBPerMonth *float32                             `json:"pricePerGBPerMonth,omitempty"`
	MinSizeGB          *int32                               `json:"minSizeGB,omitempty"`
	MaxSizeGB          *int32                               `json:"maxSizeGB,omitempty"`
	Snapshots          *PricingBlockStoragePricingSnapshots `json:"snapshots,omitempty"`
}

// NewPricingBlockStoragePricing instantiates a new PricingBlockStoragePricing object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPricingBlockStoragePricing() *PricingBlockStoragePricing {
	this := PricingBlockStoragePricing{}
	return &this
}

// NewPricingBlockStoragePricingWithDefaults instantiates a new PricingBlockStoragePricing object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPricingBlockStoragePricingWithDefaults() *PricingBlockStoragePricing {
	this := PricingBlockStoragePricing{}
	return &this
}

// GetPricePerGBPerMonth returns the PricePerGBPerMonth field value if set, zero value otherwise.
func (o *PricingBlockStoragePricing) GetPricePerGBPerMonth() float32 {
	if o == nil || IsNil(o.PricePerGBPerMonth) {
		var ret float32
		return ret
	}
	return *o.PricePerGBPerMonth
}

// GetPricePerGBPerMonthOk returns a tuple with the PricePerGBPerMonth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PricingBlockStoragePricing) GetPricePerGBPerMonthOk() (*float32, bool) {
	if o == nil || IsNil(o.PricePerGBPerMonth) {
		return nil, false
	}
	return o.PricePerGBPerMonth, true
}

// HasPricePerGBPerMonth returns a boolean if a field has been set.
func (o *PricingBlockStoragePricing) HasPricePerGBPerMonth() bool {
	if o != nil && !IsNil(o.PricePerGBPerMonth) {
		return true
	}

	return false
}

// SetPricePerGBPerMonth gets a reference to the given float32 and assigns it to the PricePerGBPerMonth field.
func (o *PricingBlockStoragePricing) SetPricePerGBPerMonth(v float32) {
	o.PricePerGBPerMonth = &v
}

// GetMinSizeGB returns the MinSizeGB field value if set, zero value otherwise.
func (o *PricingBlockStoragePricing) GetMinSizeGB() int32 {
	if o == nil || IsNil(o.MinSizeGB) {
		var ret int32
		return ret
	}
	return *o.MinSizeGB
}

// GetMinSizeGBOk returns a tuple with the MinSizeGB field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PricingBlockStoragePricing) GetMinSizeGBOk() (*int32, bool) {
	if o == nil || IsNil(o.MinSizeGB) {
		return nil, false
	}
	return o.MinSizeGB, true
}

// HasMinSizeGB returns a boolean if a field has been set.
func (o *PricingBlockStoragePricing) HasMinSizeGB() bool {
	if o != nil && !IsNil(o.MinSizeGB) {
		return true
	}

	return false
}

// SetMinSizeGB gets a reference to the given int32 and assigns it to the MinSizeGB field.
func (o *PricingBlockStoragePricing) SetMinSizeGB(v int32) {
	o.MinSizeGB = &v
}

// GetMaxSizeGB returns the MaxSizeGB field value if set, zero value otherwise.
func (o *PricingBlockStoragePricing) GetMaxSizeGB() int32 {
	if o == nil || IsNil(o.MaxSizeGB) {
		var ret int32
		return ret
	}
	return *o.MaxSizeGB
}

// GetMaxSizeGBOk returns a tuple with the MaxSizeGB field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PricingBlockStoragePricing) GetMaxSizeGBOk() (*int32, bool) {
	if o == nil || IsNil(o.MaxSizeGB) {
		return nil, false
	}
	return o.MaxSizeGB, true
}

// HasMaxSizeGB returns a boolean if a field has been set.
func (o *PricingBlockStoragePricing) HasMaxSizeGB() bool {
	if o != nil && !IsNil(o.MaxSizeGB) {
		return true
	}

	return false
}

// SetMaxSizeGB gets a reference to the given int32 and assigns it to the MaxSizeGB field.
func (o *PricingBlockStoragePricing) SetMaxSizeGB(v int32) {
	o.MaxSizeGB = &v
}

// GetSnapshots returns the Snapshots field value if set, zero value otherwise.
func (o *PricingBlockStoragePricing) GetSnapshots() PricingBlockStoragePricingSnapshots {
	if o == nil || IsNil(o.Snapshots) {
		var ret PricingBlockStoragePricingSnapshots
		return ret
	}
	return *o.Snapshots
}

// GetSnapshotsOk returns a tuple with the Snapshots field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PricingBlockStoragePricing) GetSnapshotsOk() (*PricingBlockStoragePricingSnapshots, bool) {
	if o == nil || IsNil(o.Snapshots) {
		return nil, false
	}
	return o.Snapshots, true
}

// HasSnapshots returns a boolean if a field has been set.
func (o *PricingBlockStoragePricing) HasSnapshots() bool {
	if o != nil && !IsNil(o.Snapshots) {
		return true
	}

	return false
}

// SetSnapshots gets a reference to the given PricingBlockStoragePricingSnapshots and assigns it to the Snapshots field.
func (o *PricingBlockStoragePricing) SetSnapshots(v PricingBlockStoragePricingSnapshots) {
	o.Snapshots = &v
}

func (o PricingBlockStoragePricing) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PricingBlockStoragePricing) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PricePerGBPerMonth) {
		toSerialize["pricePerGBPerMonth"] = o.PricePerGBPerMonth
	}
	if !IsNil(o.MinSizeGB) {
		toSerialize["minSizeGB"] = o.MinSizeGB
	}
	if !IsNil(o.MaxSizeGB) {
		toSerialize["maxSizeGB"] = o.MaxSizeGB
	}
	if !IsNil(o.Snapshots) {
		toSerialize["snapshots"] = o.Snapshots
	}
	return toSerialize, nil
}

type NullablePricingBlockStoragePricing struct {
	value *PricingBlockStoragePricing
	isSet bool
}

func (v NullablePricingBlockStoragePricing) Get() *PricingBlockStoragePricing {
	return v.value
}

func (v *NullablePricingBlockStoragePricing) Set(val *PricingBlockStoragePricing) {
	v.value = val
	v.isSet = true
}

func (v NullablePricingBlockStoragePricing) IsSet() bool {
	return v.isSet
}

func (v *NullablePricingBlockStoragePricing) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePricingBlockStoragePricing(val *PricingBlockStoragePricing) *NullablePricingBlockStoragePricing {
	return &NullablePricingBlockStoragePricing{value: val, isSet: true}
}

func (v NullablePricingBlockStoragePricing) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePricingBlockStoragePricing) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
