/*
Hanzo Cloud API

The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator's admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hanzoai

import (
	"encoding/json"
)

// checks if the O11yO11yQueueIn type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &O11yO11yQueueIn{}

// O11yO11yQueueIn struct for O11yO11yQueueIn
type O11yO11yQueueIn struct {
	// End is the window's end, epoch nanoseconds.
	End *int64 `json:"end,omitempty"`
	// EvalTime bounds the span-evaluation scan, nanoseconds; only the span/evaluation view reads it.
	EvalTime *int64 `json:"eval_time,omitempty"`
	// Start is the window's start, epoch nanoseconds.
	Start *int64 `json:"start,omitempty"`
	// Variables name what the view drills into — topic, partition, service, consumer_group — keyed by the name the view expects.
	Variables map[string]string `json:"variables,omitempty"`
}

// NewO11yO11yQueueIn instantiates a new O11yO11yQueueIn object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewO11yO11yQueueIn() *O11yO11yQueueIn {
	this := O11yO11yQueueIn{}
	return &this
}

// NewO11yO11yQueueInWithDefaults instantiates a new O11yO11yQueueIn object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewO11yO11yQueueInWithDefaults() *O11yO11yQueueIn {
	this := O11yO11yQueueIn{}
	return &this
}

// GetEnd returns the End field value if set, zero value otherwise.
func (o *O11yO11yQueueIn) GetEnd() int64 {
	if o == nil || IsNil(o.End) {
		var ret int64
		return ret
	}
	return *o.End
}

// GetEndOk returns a tuple with the End field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *O11yO11yQueueIn) GetEndOk() (*int64, bool) {
	if o == nil || IsNil(o.End) {
		return nil, false
	}
	return o.End, true
}

// HasEnd returns a boolean if a field has been set.
func (o *O11yO11yQueueIn) HasEnd() bool {
	if o != nil && !IsNil(o.End) {
		return true
	}

	return false
}

// SetEnd gets a reference to the given int64 and assigns it to the End field.
func (o *O11yO11yQueueIn) SetEnd(v int64) {
	o.End = &v
}

// GetEvalTime returns the EvalTime field value if set, zero value otherwise.
func (o *O11yO11yQueueIn) GetEvalTime() int64 {
	if o == nil || IsNil(o.EvalTime) {
		var ret int64
		return ret
	}
	return *o.EvalTime
}

// GetEvalTimeOk returns a tuple with the EvalTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *O11yO11yQueueIn) GetEvalTimeOk() (*int64, bool) {
	if o == nil || IsNil(o.EvalTime) {
		return nil, false
	}
	return o.EvalTime, true
}

// HasEvalTime returns a boolean if a field has been set.
func (o *O11yO11yQueueIn) HasEvalTime() bool {
	if o != nil && !IsNil(o.EvalTime) {
		return true
	}

	return false
}

// SetEvalTime gets a reference to the given int64 and assigns it to the EvalTime field.
func (o *O11yO11yQueueIn) SetEvalTime(v int64) {
	o.EvalTime = &v
}

// GetStart returns the Start field value if set, zero value otherwise.
func (o *O11yO11yQueueIn) GetStart() int64 {
	if o == nil || IsNil(o.Start) {
		var ret int64
		return ret
	}
	return *o.Start
}

// GetStartOk returns a tuple with the Start field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *O11yO11yQueueIn) GetStartOk() (*int64, bool) {
	if o == nil || IsNil(o.Start) {
		return nil, false
	}
	return o.Start, true
}

// HasStart returns a boolean if a field has been set.
func (o *O11yO11yQueueIn) HasStart() bool {
	if o != nil && !IsNil(o.Start) {
		return true
	}

	return false
}

// SetStart gets a reference to the given int64 and assigns it to the Start field.
func (o *O11yO11yQueueIn) SetStart(v int64) {
	o.Start = &v
}

// GetVariables returns the Variables field value if set, zero value otherwise.
func (o *O11yO11yQueueIn) GetVariables() map[string]string {
	if o == nil || IsNil(o.Variables) {
		var ret map[string]string
		return ret
	}
	return o.Variables
}

// GetVariablesOk returns a tuple with the Variables field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *O11yO11yQueueIn) GetVariablesOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Variables) {
		return map[string]string{}, false
	}
	return o.Variables, true
}

// HasVariables returns a boolean if a field has been set.
func (o *O11yO11yQueueIn) HasVariables() bool {
	if o != nil && !IsNil(o.Variables) {
		return true
	}

	return false
}

// SetVariables gets a reference to the given map[string]string and assigns it to the Variables field.
func (o *O11yO11yQueueIn) SetVariables(v map[string]string) {
	o.Variables = v
}

func (o O11yO11yQueueIn) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o O11yO11yQueueIn) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.End) {
		toSerialize["end"] = o.End
	}
	if !IsNil(o.EvalTime) {
		toSerialize["eval_time"] = o.EvalTime
	}
	if !IsNil(o.Start) {
		toSerialize["start"] = o.Start
	}
	if !IsNil(o.Variables) {
		toSerialize["variables"] = o.Variables
	}
	return toSerialize, nil
}

type NullableO11yO11yQueueIn struct {
	value *O11yO11yQueueIn
	isSet bool
}

func (v NullableO11yO11yQueueIn) Get() *O11yO11yQueueIn {
	return v.value
}

func (v *NullableO11yO11yQueueIn) Set(val *O11yO11yQueueIn) {
	v.value = val
	v.isSet = true
}

func (v NullableO11yO11yQueueIn) IsSet() bool {
	return v.isSet
}

func (v *NullableO11yO11yQueueIn) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableO11yO11yQueueIn(val *O11yO11yQueueIn) *NullableO11yO11yQueueIn {
	return &NullableO11yO11yQueueIn{value: val, isSet: true}
}

func (v NullableO11yO11yQueueIn) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableO11yO11yQueueIn) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
