/*
Hanzo Cloud — Unified API (V8 · Open Edition)

The single unified OpenAPI surface for ALL Hanzo services, aggregated from the per-service specs. Every route is https://api.hanzo.ai/v1/<service>/_*. Grouped by the canonical domains in capabilities.yaml (the ONE registry). cloud/openapi.yaml is hanzoai/cloud's own woven document, copied verbatim by sync.py, and it wins wherever it and a hand-written spec describe the same route. Regenerated by merge.py — edit the per-service <svc>/openapi.yaml + capabilities.yaml, not this file.

API version: 8.0.0
Contact: support@hanzo.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hanzoai

import (
	"encoding/json"
)

// checks if the CloudSampleView type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CloudSampleView{}

// CloudSampleView struct for CloudSampleView
type CloudSampleView struct {
	At        *string  `json:"at,omitempty"`
	CostCents *int32   `json:"costCents,omitempty"`
	Cpus      *int32   `json:"cpus,omitempty"`
	GpuModel  *string  `json:"gpuModel,omitempty"`
	GpuUtil   *float32 `json:"gpuUtil,omitempty"`
	Gpus      *int32   `json:"gpus,omitempty"`
	Host      *string  `json:"host,omitempty"`
	Kind      *string  `json:"kind,omitempty"`
	Load1     *float32 `json:"load1,omitempty"`
	Load5     *float32 `json:"load5,omitempty"`
	Load15    *float32 `json:"load15,omitempty"`
	MemFree   *int32   `json:"memFree,omitempty"`
	MemUsed   *int32   `json:"memUsed,omitempty"`
	Memory    *int32   `json:"memory,omitempty"`
	Source    *string  `json:"source,omitempty"`
	Unit      *string  `json:"unit,omitempty"`
}

// NewCloudSampleView instantiates a new CloudSampleView object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCloudSampleView() *CloudSampleView {
	this := CloudSampleView{}
	return &this
}

// NewCloudSampleViewWithDefaults instantiates a new CloudSampleView object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCloudSampleViewWithDefaults() *CloudSampleView {
	this := CloudSampleView{}
	return &this
}

// GetAt returns the At field value if set, zero value otherwise.
func (o *CloudSampleView) GetAt() string {
	if o == nil || IsNil(o.At) {
		var ret string
		return ret
	}
	return *o.At
}

// GetAtOk returns a tuple with the At field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudSampleView) GetAtOk() (*string, bool) {
	if o == nil || IsNil(o.At) {
		return nil, false
	}
	return o.At, true
}

// HasAt returns a boolean if a field has been set.
func (o *CloudSampleView) HasAt() bool {
	if o != nil && !IsNil(o.At) {
		return true
	}

	return false
}

// SetAt gets a reference to the given string and assigns it to the At field.
func (o *CloudSampleView) SetAt(v string) {
	o.At = &v
}

// GetCostCents returns the CostCents field value if set, zero value otherwise.
func (o *CloudSampleView) GetCostCents() int32 {
	if o == nil || IsNil(o.CostCents) {
		var ret int32
		return ret
	}
	return *o.CostCents
}

// GetCostCentsOk returns a tuple with the CostCents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudSampleView) GetCostCentsOk() (*int32, bool) {
	if o == nil || IsNil(o.CostCents) {
		return nil, false
	}
	return o.CostCents, true
}

// HasCostCents returns a boolean if a field has been set.
func (o *CloudSampleView) HasCostCents() bool {
	if o != nil && !IsNil(o.CostCents) {
		return true
	}

	return false
}

// SetCostCents gets a reference to the given int32 and assigns it to the CostCents field.
func (o *CloudSampleView) SetCostCents(v int32) {
	o.CostCents = &v
}

// GetCpus returns the Cpus field value if set, zero value otherwise.
func (o *CloudSampleView) GetCpus() int32 {
	if o == nil || IsNil(o.Cpus) {
		var ret int32
		return ret
	}
	return *o.Cpus
}

// GetCpusOk returns a tuple with the Cpus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudSampleView) GetCpusOk() (*int32, bool) {
	if o == nil || IsNil(o.Cpus) {
		return nil, false
	}
	return o.Cpus, true
}

// HasCpus returns a boolean if a field has been set.
func (o *CloudSampleView) HasCpus() bool {
	if o != nil && !IsNil(o.Cpus) {
		return true
	}

	return false
}

// SetCpus gets a reference to the given int32 and assigns it to the Cpus field.
func (o *CloudSampleView) SetCpus(v int32) {
	o.Cpus = &v
}

// GetGpuModel returns the GpuModel field value if set, zero value otherwise.
func (o *CloudSampleView) GetGpuModel() string {
	if o == nil || IsNil(o.GpuModel) {
		var ret string
		return ret
	}
	return *o.GpuModel
}

// GetGpuModelOk returns a tuple with the GpuModel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudSampleView) GetGpuModelOk() (*string, bool) {
	if o == nil || IsNil(o.GpuModel) {
		return nil, false
	}
	return o.GpuModel, true
}

// HasGpuModel returns a boolean if a field has been set.
func (o *CloudSampleView) HasGpuModel() bool {
	if o != nil && !IsNil(o.GpuModel) {
		return true
	}

	return false
}

// SetGpuModel gets a reference to the given string and assigns it to the GpuModel field.
func (o *CloudSampleView) SetGpuModel(v string) {
	o.GpuModel = &v
}

// GetGpuUtil returns the GpuUtil field value if set, zero value otherwise.
func (o *CloudSampleView) GetGpuUtil() float32 {
	if o == nil || IsNil(o.GpuUtil) {
		var ret float32
		return ret
	}
	return *o.GpuUtil
}

// GetGpuUtilOk returns a tuple with the GpuUtil field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudSampleView) GetGpuUtilOk() (*float32, bool) {
	if o == nil || IsNil(o.GpuUtil) {
		return nil, false
	}
	return o.GpuUtil, true
}

// HasGpuUtil returns a boolean if a field has been set.
func (o *CloudSampleView) HasGpuUtil() bool {
	if o != nil && !IsNil(o.GpuUtil) {
		return true
	}

	return false
}

// SetGpuUtil gets a reference to the given float32 and assigns it to the GpuUtil field.
func (o *CloudSampleView) SetGpuUtil(v float32) {
	o.GpuUtil = &v
}

// GetGpus returns the Gpus field value if set, zero value otherwise.
func (o *CloudSampleView) GetGpus() int32 {
	if o == nil || IsNil(o.Gpus) {
		var ret int32
		return ret
	}
	return *o.Gpus
}

// GetGpusOk returns a tuple with the Gpus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudSampleView) GetGpusOk() (*int32, bool) {
	if o == nil || IsNil(o.Gpus) {
		return nil, false
	}
	return o.Gpus, true
}

// HasGpus returns a boolean if a field has been set.
func (o *CloudSampleView) HasGpus() bool {
	if o != nil && !IsNil(o.Gpus) {
		return true
	}

	return false
}

// SetGpus gets a reference to the given int32 and assigns it to the Gpus field.
func (o *CloudSampleView) SetGpus(v int32) {
	o.Gpus = &v
}

// GetHost returns the Host field value if set, zero value otherwise.
func (o *CloudSampleView) GetHost() string {
	if o == nil || IsNil(o.Host) {
		var ret string
		return ret
	}
	return *o.Host
}

// GetHostOk returns a tuple with the Host field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudSampleView) GetHostOk() (*string, bool) {
	if o == nil || IsNil(o.Host) {
		return nil, false
	}
	return o.Host, true
}

// HasHost returns a boolean if a field has been set.
func (o *CloudSampleView) HasHost() bool {
	if o != nil && !IsNil(o.Host) {
		return true
	}

	return false
}

// SetHost gets a reference to the given string and assigns it to the Host field.
func (o *CloudSampleView) SetHost(v string) {
	o.Host = &v
}

// GetKind returns the Kind field value if set, zero value otherwise.
func (o *CloudSampleView) GetKind() string {
	if o == nil || IsNil(o.Kind) {
		var ret string
		return ret
	}
	return *o.Kind
}

// GetKindOk returns a tuple with the Kind field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudSampleView) GetKindOk() (*string, bool) {
	if o == nil || IsNil(o.Kind) {
		return nil, false
	}
	return o.Kind, true
}

// HasKind returns a boolean if a field has been set.
func (o *CloudSampleView) HasKind() bool {
	if o != nil && !IsNil(o.Kind) {
		return true
	}

	return false
}

// SetKind gets a reference to the given string and assigns it to the Kind field.
func (o *CloudSampleView) SetKind(v string) {
	o.Kind = &v
}

// GetLoad1 returns the Load1 field value if set, zero value otherwise.
func (o *CloudSampleView) GetLoad1() float32 {
	if o == nil || IsNil(o.Load1) {
		var ret float32
		return ret
	}
	return *o.Load1
}

// GetLoad1Ok returns a tuple with the Load1 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudSampleView) GetLoad1Ok() (*float32, bool) {
	if o == nil || IsNil(o.Load1) {
		return nil, false
	}
	return o.Load1, true
}

// HasLoad1 returns a boolean if a field has been set.
func (o *CloudSampleView) HasLoad1() bool {
	if o != nil && !IsNil(o.Load1) {
		return true
	}

	return false
}

// SetLoad1 gets a reference to the given float32 and assigns it to the Load1 field.
func (o *CloudSampleView) SetLoad1(v float32) {
	o.Load1 = &v
}

// GetLoad5 returns the Load5 field value if set, zero value otherwise.
func (o *CloudSampleView) GetLoad5() float32 {
	if o == nil || IsNil(o.Load5) {
		var ret float32
		return ret
	}
	return *o.Load5
}

// GetLoad5Ok returns a tuple with the Load5 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudSampleView) GetLoad5Ok() (*float32, bool) {
	if o == nil || IsNil(o.Load5) {
		return nil, false
	}
	return o.Load5, true
}

// HasLoad5 returns a boolean if a field has been set.
func (o *CloudSampleView) HasLoad5() bool {
	if o != nil && !IsNil(o.Load5) {
		return true
	}

	return false
}

// SetLoad5 gets a reference to the given float32 and assigns it to the Load5 field.
func (o *CloudSampleView) SetLoad5(v float32) {
	o.Load5 = &v
}

// GetLoad15 returns the Load15 field value if set, zero value otherwise.
func (o *CloudSampleView) GetLoad15() float32 {
	if o == nil || IsNil(o.Load15) {
		var ret float32
		return ret
	}
	return *o.Load15
}

// GetLoad15Ok returns a tuple with the Load15 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudSampleView) GetLoad15Ok() (*float32, bool) {
	if o == nil || IsNil(o.Load15) {
		return nil, false
	}
	return o.Load15, true
}

// HasLoad15 returns a boolean if a field has been set.
func (o *CloudSampleView) HasLoad15() bool {
	if o != nil && !IsNil(o.Load15) {
		return true
	}

	return false
}

// SetLoad15 gets a reference to the given float32 and assigns it to the Load15 field.
func (o *CloudSampleView) SetLoad15(v float32) {
	o.Load15 = &v
}

// GetMemFree returns the MemFree field value if set, zero value otherwise.
func (o *CloudSampleView) GetMemFree() int32 {
	if o == nil || IsNil(o.MemFree) {
		var ret int32
		return ret
	}
	return *o.MemFree
}

// GetMemFreeOk returns a tuple with the MemFree field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudSampleView) GetMemFreeOk() (*int32, bool) {
	if o == nil || IsNil(o.MemFree) {
		return nil, false
	}
	return o.MemFree, true
}

// HasMemFree returns a boolean if a field has been set.
func (o *CloudSampleView) HasMemFree() bool {
	if o != nil && !IsNil(o.MemFree) {
		return true
	}

	return false
}

// SetMemFree gets a reference to the given int32 and assigns it to the MemFree field.
func (o *CloudSampleView) SetMemFree(v int32) {
	o.MemFree = &v
}

// GetMemUsed returns the MemUsed field value if set, zero value otherwise.
func (o *CloudSampleView) GetMemUsed() int32 {
	if o == nil || IsNil(o.MemUsed) {
		var ret int32
		return ret
	}
	return *o.MemUsed
}

// GetMemUsedOk returns a tuple with the MemUsed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudSampleView) GetMemUsedOk() (*int32, bool) {
	if o == nil || IsNil(o.MemUsed) {
		return nil, false
	}
	return o.MemUsed, true
}

// HasMemUsed returns a boolean if a field has been set.
func (o *CloudSampleView) HasMemUsed() bool {
	if o != nil && !IsNil(o.MemUsed) {
		return true
	}

	return false
}

// SetMemUsed gets a reference to the given int32 and assigns it to the MemUsed field.
func (o *CloudSampleView) SetMemUsed(v int32) {
	o.MemUsed = &v
}

// GetMemory returns the Memory field value if set, zero value otherwise.
func (o *CloudSampleView) GetMemory() int32 {
	if o == nil || IsNil(o.Memory) {
		var ret int32
		return ret
	}
	return *o.Memory
}

// GetMemoryOk returns a tuple with the Memory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudSampleView) GetMemoryOk() (*int32, bool) {
	if o == nil || IsNil(o.Memory) {
		return nil, false
	}
	return o.Memory, true
}

// HasMemory returns a boolean if a field has been set.
func (o *CloudSampleView) HasMemory() bool {
	if o != nil && !IsNil(o.Memory) {
		return true
	}

	return false
}

// SetMemory gets a reference to the given int32 and assigns it to the Memory field.
func (o *CloudSampleView) SetMemory(v int32) {
	o.Memory = &v
}

// GetSource returns the Source field value if set, zero value otherwise.
func (o *CloudSampleView) GetSource() string {
	if o == nil || IsNil(o.Source) {
		var ret string
		return ret
	}
	return *o.Source
}

// GetSourceOk returns a tuple with the Source field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudSampleView) GetSourceOk() (*string, bool) {
	if o == nil || IsNil(o.Source) {
		return nil, false
	}
	return o.Source, true
}

// HasSource returns a boolean if a field has been set.
func (o *CloudSampleView) HasSource() bool {
	if o != nil && !IsNil(o.Source) {
		return true
	}

	return false
}

// SetSource gets a reference to the given string and assigns it to the Source field.
func (o *CloudSampleView) SetSource(v string) {
	o.Source = &v
}

// GetUnit returns the Unit field value if set, zero value otherwise.
func (o *CloudSampleView) GetUnit() string {
	if o == nil || IsNil(o.Unit) {
		var ret string
		return ret
	}
	return *o.Unit
}

// GetUnitOk returns a tuple with the Unit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudSampleView) GetUnitOk() (*string, bool) {
	if o == nil || IsNil(o.Unit) {
		return nil, false
	}
	return o.Unit, true
}

// HasUnit returns a boolean if a field has been set.
func (o *CloudSampleView) HasUnit() bool {
	if o != nil && !IsNil(o.Unit) {
		return true
	}

	return false
}

// SetUnit gets a reference to the given string and assigns it to the Unit field.
func (o *CloudSampleView) SetUnit(v string) {
	o.Unit = &v
}

func (o CloudSampleView) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CloudSampleView) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.At) {
		toSerialize["at"] = o.At
	}
	if !IsNil(o.CostCents) {
		toSerialize["costCents"] = o.CostCents
	}
	if !IsNil(o.Cpus) {
		toSerialize["cpus"] = o.Cpus
	}
	if !IsNil(o.GpuModel) {
		toSerialize["gpuModel"] = o.GpuModel
	}
	if !IsNil(o.GpuUtil) {
		toSerialize["gpuUtil"] = o.GpuUtil
	}
	if !IsNil(o.Gpus) {
		toSerialize["gpus"] = o.Gpus
	}
	if !IsNil(o.Host) {
		toSerialize["host"] = o.Host
	}
	if !IsNil(o.Kind) {
		toSerialize["kind"] = o.Kind
	}
	if !IsNil(o.Load1) {
		toSerialize["load1"] = o.Load1
	}
	if !IsNil(o.Load5) {
		toSerialize["load5"] = o.Load5
	}
	if !IsNil(o.Load15) {
		toSerialize["load15"] = o.Load15
	}
	if !IsNil(o.MemFree) {
		toSerialize["memFree"] = o.MemFree
	}
	if !IsNil(o.MemUsed) {
		toSerialize["memUsed"] = o.MemUsed
	}
	if !IsNil(o.Memory) {
		toSerialize["memory"] = o.Memory
	}
	if !IsNil(o.Source) {
		toSerialize["source"] = o.Source
	}
	if !IsNil(o.Unit) {
		toSerialize["unit"] = o.Unit
	}
	return toSerialize, nil
}

type NullableCloudSampleView struct {
	value *CloudSampleView
	isSet bool
}

func (v NullableCloudSampleView) Get() *CloudSampleView {
	return v.value
}

func (v *NullableCloudSampleView) Set(val *CloudSampleView) {
	v.value = val
	v.isSet = true
}

func (v NullableCloudSampleView) IsSet() bool {
	return v.isSet
}

func (v *NullableCloudSampleView) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCloudSampleView(val *CloudSampleView) *NullableCloudSampleView {
	return &NullableCloudSampleView{value: val, isSet: true}
}

func (v NullableCloudSampleView) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCloudSampleView) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
