/*
Hanzo Cloud API

The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator's admin product, relay doors, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hanzoai

import (
	"encoding/json"
)

// checks if the CryptoOptions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CryptoOptions{}

// CryptoOptions struct for CryptoOptions
type CryptoOptions struct {
	Chains []string `json:"chains,omitempty"`
	Tokens []string `json:"tokens,omitempty"`
}

// NewCryptoOptions instantiates a new CryptoOptions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCryptoOptions() *CryptoOptions {
	this := CryptoOptions{}
	return &this
}

// NewCryptoOptionsWithDefaults instantiates a new CryptoOptions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCryptoOptionsWithDefaults() *CryptoOptions {
	this := CryptoOptions{}
	return &this
}

// GetChains returns the Chains field value if set, zero value otherwise.
func (o *CryptoOptions) GetChains() []string {
	if o == nil || IsNil(o.Chains) {
		var ret []string
		return ret
	}
	return o.Chains
}

// GetChainsOk returns a tuple with the Chains field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CryptoOptions) GetChainsOk() ([]string, bool) {
	if o == nil || IsNil(o.Chains) {
		return nil, false
	}
	return o.Chains, true
}

// HasChains returns a boolean if a field has been set.
func (o *CryptoOptions) HasChains() bool {
	if o != nil && !IsNil(o.Chains) {
		return true
	}

	return false
}

// SetChains gets a reference to the given []string and assigns it to the Chains field.
func (o *CryptoOptions) SetChains(v []string) {
	o.Chains = v
}

// GetTokens returns the Tokens field value if set, zero value otherwise.
func (o *CryptoOptions) GetTokens() []string {
	if o == nil || IsNil(o.Tokens) {
		var ret []string
		return ret
	}
	return o.Tokens
}

// GetTokensOk returns a tuple with the Tokens field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CryptoOptions) GetTokensOk() ([]string, bool) {
	if o == nil || IsNil(o.Tokens) {
		return nil, false
	}
	return o.Tokens, true
}

// HasTokens returns a boolean if a field has been set.
func (o *CryptoOptions) HasTokens() bool {
	if o != nil && !IsNil(o.Tokens) {
		return true
	}

	return false
}

// SetTokens gets a reference to the given []string and assigns it to the Tokens field.
func (o *CryptoOptions) SetTokens(v []string) {
	o.Tokens = v
}

func (o CryptoOptions) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CryptoOptions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Chains) {
		toSerialize["chains"] = o.Chains
	}
	if !IsNil(o.Tokens) {
		toSerialize["tokens"] = o.Tokens
	}
	return toSerialize, nil
}

type NullableCryptoOptions struct {
	value *CryptoOptions
	isSet bool
}

func (v NullableCryptoOptions) Get() *CryptoOptions {
	return v.value
}

func (v *NullableCryptoOptions) Set(val *CryptoOptions) {
	v.value = val
	v.isSet = true
}

func (v NullableCryptoOptions) IsSet() bool {
	return v.isSet
}

func (v *NullableCryptoOptions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCryptoOptions(val *CryptoOptions) *NullableCryptoOptions {
	return &NullableCryptoOptions{value: val, isSet: true}
}

func (v NullableCryptoOptions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCryptoOptions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
