/*
Hanzo Cloud API

The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator's admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hanzoai

import (
	"encoding/json"
)

// checks if the RoomWork type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RoomWork{}

// RoomWork struct for RoomWork
type RoomWork struct {
	// Open is how many items are still work: everything whose status does not end it. It is the number a channel header shows.
	Open *int32 `json:"open,omitempty"`
	// Room is the room these counts are for, echoed back as it was resolved.
	Room *string `json:"room,omitempty"`
	// Status is the count per board column, carrying EVERY column this surface knows — an empty column reads 0 rather than being absent, so a caller can render the board without inventing the vocabulary. The keys are the same closed set every other operation here validates against.
	Status map[string]int32 `json:"status,omitempty"`
	// Total is every item bound to this room, settled ones included, so Total minus Open is what the room has finished.
	Total *int32 `json:"total,omitempty"`
	// Updated is when anything in this room's work last moved, in unix seconds. ABSENT when the room has no work at all: zero would read as the epoch, and a room nobody has filed anything in has no last activity rather than an infinitely old one. Total is 0 in exactly that case.
	Updated *int32 `json:"updated,omitempty"`
}

// NewRoomWork instantiates a new RoomWork object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRoomWork() *RoomWork {
	this := RoomWork{}
	return &this
}

// NewRoomWorkWithDefaults instantiates a new RoomWork object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRoomWorkWithDefaults() *RoomWork {
	this := RoomWork{}
	return &this
}

// GetOpen returns the Open field value if set, zero value otherwise.
func (o *RoomWork) GetOpen() int32 {
	if o == nil || IsNil(o.Open) {
		var ret int32
		return ret
	}
	return *o.Open
}

// GetOpenOk returns a tuple with the Open field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoomWork) GetOpenOk() (*int32, bool) {
	if o == nil || IsNil(o.Open) {
		return nil, false
	}
	return o.Open, true
}

// HasOpen returns a boolean if a field has been set.
func (o *RoomWork) HasOpen() bool {
	if o != nil && !IsNil(o.Open) {
		return true
	}

	return false
}

// SetOpen gets a reference to the given int32 and assigns it to the Open field.
func (o *RoomWork) SetOpen(v int32) {
	o.Open = &v
}

// GetRoom returns the Room field value if set, zero value otherwise.
func (o *RoomWork) GetRoom() string {
	if o == nil || IsNil(o.Room) {
		var ret string
		return ret
	}
	return *o.Room
}

// GetRoomOk returns a tuple with the Room field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoomWork) GetRoomOk() (*string, bool) {
	if o == nil || IsNil(o.Room) {
		return nil, false
	}
	return o.Room, true
}

// HasRoom returns a boolean if a field has been set.
func (o *RoomWork) HasRoom() bool {
	if o != nil && !IsNil(o.Room) {
		return true
	}

	return false
}

// SetRoom gets a reference to the given string and assigns it to the Room field.
func (o *RoomWork) SetRoom(v string) {
	o.Room = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *RoomWork) GetStatus() map[string]int32 {
	if o == nil || IsNil(o.Status) {
		var ret map[string]int32
		return ret
	}
	return o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoomWork) GetStatusOk() (map[string]int32, bool) {
	if o == nil || IsNil(o.Status) {
		return map[string]int32{}, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *RoomWork) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given map[string]int32 and assigns it to the Status field.
func (o *RoomWork) SetStatus(v map[string]int32) {
	o.Status = v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *RoomWork) GetTotal() int32 {
	if o == nil || IsNil(o.Total) {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoomWork) GetTotalOk() (*int32, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *RoomWork) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *RoomWork) SetTotal(v int32) {
	o.Total = &v
}

// GetUpdated returns the Updated field value if set, zero value otherwise.
func (o *RoomWork) GetUpdated() int32 {
	if o == nil || IsNil(o.Updated) {
		var ret int32
		return ret
	}
	return *o.Updated
}

// GetUpdatedOk returns a tuple with the Updated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoomWork) GetUpdatedOk() (*int32, bool) {
	if o == nil || IsNil(o.Updated) {
		return nil, false
	}
	return o.Updated, true
}

// HasUpdated returns a boolean if a field has been set.
func (o *RoomWork) HasUpdated() bool {
	if o != nil && !IsNil(o.Updated) {
		return true
	}

	return false
}

// SetUpdated gets a reference to the given int32 and assigns it to the Updated field.
func (o *RoomWork) SetUpdated(v int32) {
	o.Updated = &v
}

func (o RoomWork) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RoomWork) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Open) {
		toSerialize["open"] = o.Open
	}
	if !IsNil(o.Room) {
		toSerialize["room"] = o.Room
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	if !IsNil(o.Updated) {
		toSerialize["updated"] = o.Updated
	}
	return toSerialize, nil
}

type NullableRoomWork struct {
	value *RoomWork
	isSet bool
}

func (v NullableRoomWork) Get() *RoomWork {
	return v.value
}

func (v *NullableRoomWork) Set(val *RoomWork) {
	v.value = val
	v.isSet = true
}

func (v NullableRoomWork) IsSet() bool {
	return v.isSet
}

func (v *NullableRoomWork) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRoomWork(val *RoomWork) *NullableRoomWork {
	return &NullableRoomWork{value: val, isSet: true}
}

func (v NullableRoomWork) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRoomWork) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
