/*
Hanzo Cloud API

Composed from each subsystem's own projection of its router, in the fleet's mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hanzoai

import (
	"encoding/json"
)

// checks if the EnrollInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EnrollInput{}

// EnrollInput struct for EnrollInput
type EnrollInput struct {
	// Address is a single recipient, normalized (lower-cased, trimmed) before use. Give this OR audienceId, never both and never neither.
	Address *string `json:"address,omitempty"`
	// AudienceID fans the sequence out over a saved audience, resolved live to the org's mailable customers. Email only.
	AudienceId *string `json:"audienceId,omitempty"`
	// Channel is the delivery surface; empty means email. An audience resolves mailboxes, so an audience enroll must be email.
	Channel *string `json:"channel,omitempty"`
	// ID is the sequence id from the path.
	Id *string `json:"id,omitempty"`
}

// NewEnrollInput instantiates a new EnrollInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEnrollInput() *EnrollInput {
	this := EnrollInput{}
	return &this
}

// NewEnrollInputWithDefaults instantiates a new EnrollInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEnrollInputWithDefaults() *EnrollInput {
	this := EnrollInput{}
	return &this
}

// GetAddress returns the Address field value if set, zero value otherwise.
func (o *EnrollInput) GetAddress() string {
	if o == nil || IsNil(o.Address) {
		var ret string
		return ret
	}
	return *o.Address
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnrollInput) GetAddressOk() (*string, bool) {
	if o == nil || IsNil(o.Address) {
		return nil, false
	}
	return o.Address, true
}

// HasAddress returns a boolean if a field has been set.
func (o *EnrollInput) HasAddress() bool {
	if o != nil && !IsNil(o.Address) {
		return true
	}

	return false
}

// SetAddress gets a reference to the given string and assigns it to the Address field.
func (o *EnrollInput) SetAddress(v string) {
	o.Address = &v
}

// GetAudienceId returns the AudienceId field value if set, zero value otherwise.
func (o *EnrollInput) GetAudienceId() string {
	if o == nil || IsNil(o.AudienceId) {
		var ret string
		return ret
	}
	return *o.AudienceId
}

// GetAudienceIdOk returns a tuple with the AudienceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnrollInput) GetAudienceIdOk() (*string, bool) {
	if o == nil || IsNil(o.AudienceId) {
		return nil, false
	}
	return o.AudienceId, true
}

// HasAudienceId returns a boolean if a field has been set.
func (o *EnrollInput) HasAudienceId() bool {
	if o != nil && !IsNil(o.AudienceId) {
		return true
	}

	return false
}

// SetAudienceId gets a reference to the given string and assigns it to the AudienceId field.
func (o *EnrollInput) SetAudienceId(v string) {
	o.AudienceId = &v
}

// GetChannel returns the Channel field value if set, zero value otherwise.
func (o *EnrollInput) GetChannel() string {
	if o == nil || IsNil(o.Channel) {
		var ret string
		return ret
	}
	return *o.Channel
}

// GetChannelOk returns a tuple with the Channel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnrollInput) GetChannelOk() (*string, bool) {
	if o == nil || IsNil(o.Channel) {
		return nil, false
	}
	return o.Channel, true
}

// HasChannel returns a boolean if a field has been set.
func (o *EnrollInput) HasChannel() bool {
	if o != nil && !IsNil(o.Channel) {
		return true
	}

	return false
}

// SetChannel gets a reference to the given string and assigns it to the Channel field.
func (o *EnrollInput) SetChannel(v string) {
	o.Channel = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *EnrollInput) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnrollInput) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *EnrollInput) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *EnrollInput) SetId(v string) {
	o.Id = &v
}

func (o EnrollInput) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EnrollInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Address) {
		toSerialize["address"] = o.Address
	}
	if !IsNil(o.AudienceId) {
		toSerialize["audienceId"] = o.AudienceId
	}
	if !IsNil(o.Channel) {
		toSerialize["channel"] = o.Channel
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	return toSerialize, nil
}

type NullableEnrollInput struct {
	value *EnrollInput
	isSet bool
}

func (v NullableEnrollInput) Get() *EnrollInput {
	return v.value
}

func (v *NullableEnrollInput) Set(val *EnrollInput) {
	v.value = val
	v.isSet = true
}

func (v NullableEnrollInput) IsSet() bool {
	return v.isSet
}

func (v *NullableEnrollInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnrollInput(val *EnrollInput) *NullableEnrollInput {
	return &NullableEnrollInput{value: val, isSet: true}
}

func (v NullableEnrollInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnrollInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
