/*
Hanzo Cloud — Unified API (V8 · Open Edition)

The single unified OpenAPI surface for ALL Hanzo services, aggregated from the per-service specs. Every route is https://api.hanzo.ai/v1/<service>/_*. Grouped by the canonical domains in capabilities.yaml (the ONE registry). Regenerated by merge.py — edit the per-service <svc>/openapi.yaml + capabilities.yaml, not this file.

API version: 8.0.0
Contact: support@hanzo.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hanzoai

import (
	"encoding/json"
)

// checks if the AuthorsAdminSweepEnvelopeAllOfData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuthorsAdminSweepEnvelopeAllOfData{}

// AuthorsAdminSweepEnvelopeAllOfData struct for AuthorsAdminSweepEnvelopeAllOfData
type AuthorsAdminSweepEnvelopeAllOfData struct {
	// Deploying-org checks performed across all approved authors.
	Swept *int32 `json:"swept,omitempty"`
	// Accruals newly created.
	Accrued *int32 `json:"accrued,omitempty"`
}

// NewAuthorsAdminSweepEnvelopeAllOfData instantiates a new AuthorsAdminSweepEnvelopeAllOfData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthorsAdminSweepEnvelopeAllOfData() *AuthorsAdminSweepEnvelopeAllOfData {
	this := AuthorsAdminSweepEnvelopeAllOfData{}
	return &this
}

// NewAuthorsAdminSweepEnvelopeAllOfDataWithDefaults instantiates a new AuthorsAdminSweepEnvelopeAllOfData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthorsAdminSweepEnvelopeAllOfDataWithDefaults() *AuthorsAdminSweepEnvelopeAllOfData {
	this := AuthorsAdminSweepEnvelopeAllOfData{}
	return &this
}

// GetSwept returns the Swept field value if set, zero value otherwise.
func (o *AuthorsAdminSweepEnvelopeAllOfData) GetSwept() int32 {
	if o == nil || IsNil(o.Swept) {
		var ret int32
		return ret
	}
	return *o.Swept
}

// GetSweptOk returns a tuple with the Swept field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthorsAdminSweepEnvelopeAllOfData) GetSweptOk() (*int32, bool) {
	if o == nil || IsNil(o.Swept) {
		return nil, false
	}
	return o.Swept, true
}

// HasSwept returns a boolean if a field has been set.
func (o *AuthorsAdminSweepEnvelopeAllOfData) HasSwept() bool {
	if o != nil && !IsNil(o.Swept) {
		return true
	}

	return false
}

// SetSwept gets a reference to the given int32 and assigns it to the Swept field.
func (o *AuthorsAdminSweepEnvelopeAllOfData) SetSwept(v int32) {
	o.Swept = &v
}

// GetAccrued returns the Accrued field value if set, zero value otherwise.
func (o *AuthorsAdminSweepEnvelopeAllOfData) GetAccrued() int32 {
	if o == nil || IsNil(o.Accrued) {
		var ret int32
		return ret
	}
	return *o.Accrued
}

// GetAccruedOk returns a tuple with the Accrued field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthorsAdminSweepEnvelopeAllOfData) GetAccruedOk() (*int32, bool) {
	if o == nil || IsNil(o.Accrued) {
		return nil, false
	}
	return o.Accrued, true
}

// HasAccrued returns a boolean if a field has been set.
func (o *AuthorsAdminSweepEnvelopeAllOfData) HasAccrued() bool {
	if o != nil && !IsNil(o.Accrued) {
		return true
	}

	return false
}

// SetAccrued gets a reference to the given int32 and assigns it to the Accrued field.
func (o *AuthorsAdminSweepEnvelopeAllOfData) SetAccrued(v int32) {
	o.Accrued = &v
}

func (o AuthorsAdminSweepEnvelopeAllOfData) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuthorsAdminSweepEnvelopeAllOfData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Swept) {
		toSerialize["swept"] = o.Swept
	}
	if !IsNil(o.Accrued) {
		toSerialize["accrued"] = o.Accrued
	}
	return toSerialize, nil
}

type NullableAuthorsAdminSweepEnvelopeAllOfData struct {
	value *AuthorsAdminSweepEnvelopeAllOfData
	isSet bool
}

func (v NullableAuthorsAdminSweepEnvelopeAllOfData) Get() *AuthorsAdminSweepEnvelopeAllOfData {
	return v.value
}

func (v *NullableAuthorsAdminSweepEnvelopeAllOfData) Set(val *AuthorsAdminSweepEnvelopeAllOfData) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthorsAdminSweepEnvelopeAllOfData) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthorsAdminSweepEnvelopeAllOfData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthorsAdminSweepEnvelopeAllOfData(val *AuthorsAdminSweepEnvelopeAllOfData) *NullableAuthorsAdminSweepEnvelopeAllOfData {
	return &NullableAuthorsAdminSweepEnvelopeAllOfData{value: val, isSet: true}
}

func (v NullableAuthorsAdminSweepEnvelopeAllOfData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthorsAdminSweepEnvelopeAllOfData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
