/*
Hanzo Cloud API

The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator's admin product, relay doors, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hanzoai

import (
	"encoding/json"
)

// checks if the MintedKey type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MintedKey{}

// MintedKey struct for MintedKey
type MintedKey struct {
	// AccessKey is the same value under its predecessor name, carried so callers written against the older field keep working. One value, two names.
	AccessKey *string `json:"accessKey,omitempty"`
	// Key is the credential, returned ONCE — a secret key is unreadable afterwards.
	Key *string `json:"key,omitempty"`
	// Limit is what the minted key may reach, echoed back so the caller can see the narrowing took. Absent means unrestricted.
	Limit []string `json:"limit,omitempty"`
	// Type is the class of key that was minted.
	Type *string `json:"type,omitempty"`
}

// NewMintedKey instantiates a new MintedKey object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMintedKey() *MintedKey {
	this := MintedKey{}
	return &this
}

// NewMintedKeyWithDefaults instantiates a new MintedKey object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMintedKeyWithDefaults() *MintedKey {
	this := MintedKey{}
	return &this
}

// GetAccessKey returns the AccessKey field value if set, zero value otherwise.
func (o *MintedKey) GetAccessKey() string {
	if o == nil || IsNil(o.AccessKey) {
		var ret string
		return ret
	}
	return *o.AccessKey
}

// GetAccessKeyOk returns a tuple with the AccessKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MintedKey) GetAccessKeyOk() (*string, bool) {
	if o == nil || IsNil(o.AccessKey) {
		return nil, false
	}
	return o.AccessKey, true
}

// HasAccessKey returns a boolean if a field has been set.
func (o *MintedKey) HasAccessKey() bool {
	if o != nil && !IsNil(o.AccessKey) {
		return true
	}

	return false
}

// SetAccessKey gets a reference to the given string and assigns it to the AccessKey field.
func (o *MintedKey) SetAccessKey(v string) {
	o.AccessKey = &v
}

// GetKey returns the Key field value if set, zero value otherwise.
func (o *MintedKey) GetKey() string {
	if o == nil || IsNil(o.Key) {
		var ret string
		return ret
	}
	return *o.Key
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MintedKey) GetKeyOk() (*string, bool) {
	if o == nil || IsNil(o.Key) {
		return nil, false
	}
	return o.Key, true
}

// HasKey returns a boolean if a field has been set.
func (o *MintedKey) HasKey() bool {
	if o != nil && !IsNil(o.Key) {
		return true
	}

	return false
}

// SetKey gets a reference to the given string and assigns it to the Key field.
func (o *MintedKey) SetKey(v string) {
	o.Key = &v
}

// GetLimit returns the Limit field value if set, zero value otherwise.
func (o *MintedKey) GetLimit() []string {
	if o == nil || IsNil(o.Limit) {
		var ret []string
		return ret
	}
	return o.Limit
}

// GetLimitOk returns a tuple with the Limit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MintedKey) GetLimitOk() ([]string, bool) {
	if o == nil || IsNil(o.Limit) {
		return nil, false
	}
	return o.Limit, true
}

// HasLimit returns a boolean if a field has been set.
func (o *MintedKey) HasLimit() bool {
	if o != nil && !IsNil(o.Limit) {
		return true
	}

	return false
}

// SetLimit gets a reference to the given []string and assigns it to the Limit field.
func (o *MintedKey) SetLimit(v []string) {
	o.Limit = v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *MintedKey) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MintedKey) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *MintedKey) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *MintedKey) SetType(v string) {
	o.Type = &v
}

func (o MintedKey) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MintedKey) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AccessKey) {
		toSerialize["accessKey"] = o.AccessKey
	}
	if !IsNil(o.Key) {
		toSerialize["key"] = o.Key
	}
	if !IsNil(o.Limit) {
		toSerialize["limit"] = o.Limit
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	return toSerialize, nil
}

type NullableMintedKey struct {
	value *MintedKey
	isSet bool
}

func (v NullableMintedKey) Get() *MintedKey {
	return v.value
}

func (v *NullableMintedKey) Set(val *MintedKey) {
	v.value = val
	v.isSet = true
}

func (v NullableMintedKey) IsSet() bool {
	return v.isSet
}

func (v *NullableMintedKey) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMintedKey(val *MintedKey) *NullableMintedKey {
	return &NullableMintedKey{value: val, isSet: true}
}

func (v NullableMintedKey) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMintedKey) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
