/*
Hanzo Cloud — Unified API (V8 · Open Edition)

The single unified OpenAPI surface for ALL Hanzo services, aggregated from the per-service specs. Every route is https://api.hanzo.ai/v1/<service>/_*. Grouped by the canonical domains in capabilities.yaml (the ONE registry). cloud/openapi.yaml is hanzoai/cloud's own woven document, copied verbatim by sync.py, and it wins wherever it and a hand-written spec describe the same route. Regenerated by merge.py — edit the per-service <svc>/openapi.yaml + capabilities.yaml, not this file.

API version: 8.0.0
Contact: support@hanzo.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hanzoai

import (
	"encoding/json"
)

// checks if the CloudChannelMetric type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CloudChannelMetric{}

// CloudChannelMetric struct for CloudChannelMetric
type CloudChannelMetric struct {
	ExternalId *string `json:"externalId,omitempty"`
	Kind       *string `json:"kind,omitempty"`
	Platform   *string `json:"platform,omitempty"`
	SpendCents *int32  `json:"spendCents,omitempty"`
	// honest: connector spend read failed
	SpendError *string `json:"spendError,omitempty"`
	Status     *string `json:"status,omitempty"`
}

// NewCloudChannelMetric instantiates a new CloudChannelMetric object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCloudChannelMetric() *CloudChannelMetric {
	this := CloudChannelMetric{}
	return &this
}

// NewCloudChannelMetricWithDefaults instantiates a new CloudChannelMetric object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCloudChannelMetricWithDefaults() *CloudChannelMetric {
	this := CloudChannelMetric{}
	return &this
}

// GetExternalId returns the ExternalId field value if set, zero value otherwise.
func (o *CloudChannelMetric) GetExternalId() string {
	if o == nil || IsNil(o.ExternalId) {
		var ret string
		return ret
	}
	return *o.ExternalId
}

// GetExternalIdOk returns a tuple with the ExternalId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudChannelMetric) GetExternalIdOk() (*string, bool) {
	if o == nil || IsNil(o.ExternalId) {
		return nil, false
	}
	return o.ExternalId, true
}

// HasExternalId returns a boolean if a field has been set.
func (o *CloudChannelMetric) HasExternalId() bool {
	if o != nil && !IsNil(o.ExternalId) {
		return true
	}

	return false
}

// SetExternalId gets a reference to the given string and assigns it to the ExternalId field.
func (o *CloudChannelMetric) SetExternalId(v string) {
	o.ExternalId = &v
}

// GetKind returns the Kind field value if set, zero value otherwise.
func (o *CloudChannelMetric) GetKind() string {
	if o == nil || IsNil(o.Kind) {
		var ret string
		return ret
	}
	return *o.Kind
}

// GetKindOk returns a tuple with the Kind field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudChannelMetric) GetKindOk() (*string, bool) {
	if o == nil || IsNil(o.Kind) {
		return nil, false
	}
	return o.Kind, true
}

// HasKind returns a boolean if a field has been set.
func (o *CloudChannelMetric) HasKind() bool {
	if o != nil && !IsNil(o.Kind) {
		return true
	}

	return false
}

// SetKind gets a reference to the given string and assigns it to the Kind field.
func (o *CloudChannelMetric) SetKind(v string) {
	o.Kind = &v
}

// GetPlatform returns the Platform field value if set, zero value otherwise.
func (o *CloudChannelMetric) GetPlatform() string {
	if o == nil || IsNil(o.Platform) {
		var ret string
		return ret
	}
	return *o.Platform
}

// GetPlatformOk returns a tuple with the Platform field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudChannelMetric) GetPlatformOk() (*string, bool) {
	if o == nil || IsNil(o.Platform) {
		return nil, false
	}
	return o.Platform, true
}

// HasPlatform returns a boolean if a field has been set.
func (o *CloudChannelMetric) HasPlatform() bool {
	if o != nil && !IsNil(o.Platform) {
		return true
	}

	return false
}

// SetPlatform gets a reference to the given string and assigns it to the Platform field.
func (o *CloudChannelMetric) SetPlatform(v string) {
	o.Platform = &v
}

// GetSpendCents returns the SpendCents field value if set, zero value otherwise.
func (o *CloudChannelMetric) GetSpendCents() int32 {
	if o == nil || IsNil(o.SpendCents) {
		var ret int32
		return ret
	}
	return *o.SpendCents
}

// GetSpendCentsOk returns a tuple with the SpendCents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudChannelMetric) GetSpendCentsOk() (*int32, bool) {
	if o == nil || IsNil(o.SpendCents) {
		return nil, false
	}
	return o.SpendCents, true
}

// HasSpendCents returns a boolean if a field has been set.
func (o *CloudChannelMetric) HasSpendCents() bool {
	if o != nil && !IsNil(o.SpendCents) {
		return true
	}

	return false
}

// SetSpendCents gets a reference to the given int32 and assigns it to the SpendCents field.
func (o *CloudChannelMetric) SetSpendCents(v int32) {
	o.SpendCents = &v
}

// GetSpendError returns the SpendError field value if set, zero value otherwise.
func (o *CloudChannelMetric) GetSpendError() string {
	if o == nil || IsNil(o.SpendError) {
		var ret string
		return ret
	}
	return *o.SpendError
}

// GetSpendErrorOk returns a tuple with the SpendError field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudChannelMetric) GetSpendErrorOk() (*string, bool) {
	if o == nil || IsNil(o.SpendError) {
		return nil, false
	}
	return o.SpendError, true
}

// HasSpendError returns a boolean if a field has been set.
func (o *CloudChannelMetric) HasSpendError() bool {
	if o != nil && !IsNil(o.SpendError) {
		return true
	}

	return false
}

// SetSpendError gets a reference to the given string and assigns it to the SpendError field.
func (o *CloudChannelMetric) SetSpendError(v string) {
	o.SpendError = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *CloudChannelMetric) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudChannelMetric) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *CloudChannelMetric) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *CloudChannelMetric) SetStatus(v string) {
	o.Status = &v
}

func (o CloudChannelMetric) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CloudChannelMetric) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ExternalId) {
		toSerialize["externalId"] = o.ExternalId
	}
	if !IsNil(o.Kind) {
		toSerialize["kind"] = o.Kind
	}
	if !IsNil(o.Platform) {
		toSerialize["platform"] = o.Platform
	}
	if !IsNil(o.SpendCents) {
		toSerialize["spendCents"] = o.SpendCents
	}
	if !IsNil(o.SpendError) {
		toSerialize["spendError"] = o.SpendError
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableCloudChannelMetric struct {
	value *CloudChannelMetric
	isSet bool
}

func (v NullableCloudChannelMetric) Get() *CloudChannelMetric {
	return v.value
}

func (v *NullableCloudChannelMetric) Set(val *CloudChannelMetric) {
	v.value = val
	v.isSet = true
}

func (v NullableCloudChannelMetric) IsSet() bool {
	return v.isSet
}

func (v *NullableCloudChannelMetric) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCloudChannelMetric(val *CloudChannelMetric) *NullableCloudChannelMetric {
	return &NullableCloudChannelMetric{value: val, isSet: true}
}

func (v NullableCloudChannelMetric) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCloudChannelMetric) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
