/*
Hanzo Cloud — Unified API

The single unified OpenAPI surface for ALL Hanzo services, aggregated from the per-service specs. Every route is https://api.hanzo.ai/v1/<service>/_*. Regenerated by merge.py — edit the per-service <svc>/openapi.yaml, not this file.

API version: 1.0.0
Contact: support@hanzo.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hanzoai

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the KmsCreateSecretTagRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KmsCreateSecretTagRequest{}

// KmsCreateSecretTagRequest struct for KmsCreateSecretTagRequest
type KmsCreateSecretTagRequest struct {
	Name  string `json:"name"`
	Slug  string `json:"slug"`
	Color string `json:"color"`
}

type _KmsCreateSecretTagRequest KmsCreateSecretTagRequest

// NewKmsCreateSecretTagRequest instantiates a new KmsCreateSecretTagRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKmsCreateSecretTagRequest(name string, slug string, color string) *KmsCreateSecretTagRequest {
	this := KmsCreateSecretTagRequest{}
	this.Name = name
	this.Slug = slug
	this.Color = color
	return &this
}

// NewKmsCreateSecretTagRequestWithDefaults instantiates a new KmsCreateSecretTagRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKmsCreateSecretTagRequestWithDefaults() *KmsCreateSecretTagRequest {
	this := KmsCreateSecretTagRequest{}
	return &this
}

// GetName returns the Name field value
func (o *KmsCreateSecretTagRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *KmsCreateSecretTagRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *KmsCreateSecretTagRequest) SetName(v string) {
	o.Name = v
}

// GetSlug returns the Slug field value
func (o *KmsCreateSecretTagRequest) GetSlug() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Slug
}

// GetSlugOk returns a tuple with the Slug field value
// and a boolean to check if the value has been set.
func (o *KmsCreateSecretTagRequest) GetSlugOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Slug, true
}

// SetSlug sets field value
func (o *KmsCreateSecretTagRequest) SetSlug(v string) {
	o.Slug = v
}

// GetColor returns the Color field value
func (o *KmsCreateSecretTagRequest) GetColor() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Color
}

// GetColorOk returns a tuple with the Color field value
// and a boolean to check if the value has been set.
func (o *KmsCreateSecretTagRequest) GetColorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Color, true
}

// SetColor sets field value
func (o *KmsCreateSecretTagRequest) SetColor(v string) {
	o.Color = v
}

func (o KmsCreateSecretTagRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KmsCreateSecretTagRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["slug"] = o.Slug
	toSerialize["color"] = o.Color
	return toSerialize, nil
}

func (o *KmsCreateSecretTagRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"slug",
		"color",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varKmsCreateSecretTagRequest := _KmsCreateSecretTagRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varKmsCreateSecretTagRequest)

	if err != nil {
		return err
	}

	*o = KmsCreateSecretTagRequest(varKmsCreateSecretTagRequest)

	return err
}

type NullableKmsCreateSecretTagRequest struct {
	value *KmsCreateSecretTagRequest
	isSet bool
}

func (v NullableKmsCreateSecretTagRequest) Get() *KmsCreateSecretTagRequest {
	return v.value
}

func (v *NullableKmsCreateSecretTagRequest) Set(val *KmsCreateSecretTagRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableKmsCreateSecretTagRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableKmsCreateSecretTagRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKmsCreateSecretTagRequest(val *KmsCreateSecretTagRequest) *NullableKmsCreateSecretTagRequest {
	return &NullableKmsCreateSecretTagRequest{value: val, isSet: true}
}

func (v NullableKmsCreateSecretTagRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKmsCreateSecretTagRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
