/*
Hanzo Cloud API

The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator's admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hanzoai

import (
	"encoding/json"
)

// checks if the O11yO11yDashboardViewData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &O11yO11yDashboardViewData{}

// O11yO11yDashboardViewData struct for O11yO11yDashboardViewData
type O11yO11yDashboardViewData struct {
	// Order is the captured sort direction.
	Order *string `json:"order,omitempty"`
	// Query is the captured filter DSL.
	Query *string `json:"query,omitempty"`
	// Sort is the captured sort field.
	Sort *string `json:"sort,omitempty"`
	// Version is the saved-view schema version; must be v1.
	Version *string `json:"version,omitempty"`
}

// NewO11yO11yDashboardViewData instantiates a new O11yO11yDashboardViewData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewO11yO11yDashboardViewData() *O11yO11yDashboardViewData {
	this := O11yO11yDashboardViewData{}
	return &this
}

// NewO11yO11yDashboardViewDataWithDefaults instantiates a new O11yO11yDashboardViewData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewO11yO11yDashboardViewDataWithDefaults() *O11yO11yDashboardViewData {
	this := O11yO11yDashboardViewData{}
	return &this
}

// GetOrder returns the Order field value if set, zero value otherwise.
func (o *O11yO11yDashboardViewData) GetOrder() string {
	if o == nil || IsNil(o.Order) {
		var ret string
		return ret
	}
	return *o.Order
}

// GetOrderOk returns a tuple with the Order field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *O11yO11yDashboardViewData) GetOrderOk() (*string, bool) {
	if o == nil || IsNil(o.Order) {
		return nil, false
	}
	return o.Order, true
}

// HasOrder returns a boolean if a field has been set.
func (o *O11yO11yDashboardViewData) HasOrder() bool {
	if o != nil && !IsNil(o.Order) {
		return true
	}

	return false
}

// SetOrder gets a reference to the given string and assigns it to the Order field.
func (o *O11yO11yDashboardViewData) SetOrder(v string) {
	o.Order = &v
}

// GetQuery returns the Query field value if set, zero value otherwise.
func (o *O11yO11yDashboardViewData) GetQuery() string {
	if o == nil || IsNil(o.Query) {
		var ret string
		return ret
	}
	return *o.Query
}

// GetQueryOk returns a tuple with the Query field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *O11yO11yDashboardViewData) GetQueryOk() (*string, bool) {
	if o == nil || IsNil(o.Query) {
		return nil, false
	}
	return o.Query, true
}

// HasQuery returns a boolean if a field has been set.
func (o *O11yO11yDashboardViewData) HasQuery() bool {
	if o != nil && !IsNil(o.Query) {
		return true
	}

	return false
}

// SetQuery gets a reference to the given string and assigns it to the Query field.
func (o *O11yO11yDashboardViewData) SetQuery(v string) {
	o.Query = &v
}

// GetSort returns the Sort field value if set, zero value otherwise.
func (o *O11yO11yDashboardViewData) GetSort() string {
	if o == nil || IsNil(o.Sort) {
		var ret string
		return ret
	}
	return *o.Sort
}

// GetSortOk returns a tuple with the Sort field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *O11yO11yDashboardViewData) GetSortOk() (*string, bool) {
	if o == nil || IsNil(o.Sort) {
		return nil, false
	}
	return o.Sort, true
}

// HasSort returns a boolean if a field has been set.
func (o *O11yO11yDashboardViewData) HasSort() bool {
	if o != nil && !IsNil(o.Sort) {
		return true
	}

	return false
}

// SetSort gets a reference to the given string and assigns it to the Sort field.
func (o *O11yO11yDashboardViewData) SetSort(v string) {
	o.Sort = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *O11yO11yDashboardViewData) GetVersion() string {
	if o == nil || IsNil(o.Version) {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *O11yO11yDashboardViewData) GetVersionOk() (*string, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *O11yO11yDashboardViewData) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *O11yO11yDashboardViewData) SetVersion(v string) {
	o.Version = &v
}

func (o O11yO11yDashboardViewData) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o O11yO11yDashboardViewData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Order) {
		toSerialize["order"] = o.Order
	}
	if !IsNil(o.Query) {
		toSerialize["query"] = o.Query
	}
	if !IsNil(o.Sort) {
		toSerialize["sort"] = o.Sort
	}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	return toSerialize, nil
}

type NullableO11yO11yDashboardViewData struct {
	value *O11yO11yDashboardViewData
	isSet bool
}

func (v NullableO11yO11yDashboardViewData) Get() *O11yO11yDashboardViewData {
	return v.value
}

func (v *NullableO11yO11yDashboardViewData) Set(val *O11yO11yDashboardViewData) {
	v.value = val
	v.isSet = true
}

func (v NullableO11yO11yDashboardViewData) IsSet() bool {
	return v.isSet
}

func (v *NullableO11yO11yDashboardViewData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableO11yO11yDashboardViewData(val *O11yO11yDashboardViewData) *NullableO11yO11yDashboardViewData {
	return &NullableO11yO11yDashboardViewData{value: val, isSet: true}
}

func (v NullableO11yO11yDashboardViewData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableO11yO11yDashboardViewData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
