/*
Hanzo Cloud API

Composed from each subsystem's own projection of its router, in the fleet's mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hanzoai

import (
	"encoding/json"
)

// checks if the InvoiceLineIn type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InvoiceLineIn{}

// InvoiceLineIn struct for InvoiceLineIn
type InvoiceLineIn struct {
	// Amount is the line total in whole cents (250000 is $2,500.00).
	Amount *int32 `json:"amount,omitempty"`
	// Description is the human-readable line, e.g. \"Advisory retainer — August\".
	Description *string `json:"description,omitempty"`
	// Quantity is the number of units, when the line is metered. Optional.
	Quantity *int32 `json:"quantity,omitempty"`
	// UnitPrice is the per-unit price in cents, when the line is metered. Optional.
	UnitPrice *int32 `json:"unitPrice,omitempty"`
}

// NewInvoiceLineIn instantiates a new InvoiceLineIn object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInvoiceLineIn() *InvoiceLineIn {
	this := InvoiceLineIn{}
	return &this
}

// NewInvoiceLineInWithDefaults instantiates a new InvoiceLineIn object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInvoiceLineInWithDefaults() *InvoiceLineIn {
	this := InvoiceLineIn{}
	return &this
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *InvoiceLineIn) GetAmount() int32 {
	if o == nil || IsNil(o.Amount) {
		var ret int32
		return ret
	}
	return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoiceLineIn) GetAmountOk() (*int32, bool) {
	if o == nil || IsNil(o.Amount) {
		return nil, false
	}
	return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *InvoiceLineIn) HasAmount() bool {
	if o != nil && !IsNil(o.Amount) {
		return true
	}

	return false
}

// SetAmount gets a reference to the given int32 and assigns it to the Amount field.
func (o *InvoiceLineIn) SetAmount(v int32) {
	o.Amount = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *InvoiceLineIn) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoiceLineIn) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *InvoiceLineIn) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *InvoiceLineIn) SetDescription(v string) {
	o.Description = &v
}

// GetQuantity returns the Quantity field value if set, zero value otherwise.
func (o *InvoiceLineIn) GetQuantity() int32 {
	if o == nil || IsNil(o.Quantity) {
		var ret int32
		return ret
	}
	return *o.Quantity
}

// GetQuantityOk returns a tuple with the Quantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoiceLineIn) GetQuantityOk() (*int32, bool) {
	if o == nil || IsNil(o.Quantity) {
		return nil, false
	}
	return o.Quantity, true
}

// HasQuantity returns a boolean if a field has been set.
func (o *InvoiceLineIn) HasQuantity() bool {
	if o != nil && !IsNil(o.Quantity) {
		return true
	}

	return false
}

// SetQuantity gets a reference to the given int32 and assigns it to the Quantity field.
func (o *InvoiceLineIn) SetQuantity(v int32) {
	o.Quantity = &v
}

// GetUnitPrice returns the UnitPrice field value if set, zero value otherwise.
func (o *InvoiceLineIn) GetUnitPrice() int32 {
	if o == nil || IsNil(o.UnitPrice) {
		var ret int32
		return ret
	}
	return *o.UnitPrice
}

// GetUnitPriceOk returns a tuple with the UnitPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoiceLineIn) GetUnitPriceOk() (*int32, bool) {
	if o == nil || IsNil(o.UnitPrice) {
		return nil, false
	}
	return o.UnitPrice, true
}

// HasUnitPrice returns a boolean if a field has been set.
func (o *InvoiceLineIn) HasUnitPrice() bool {
	if o != nil && !IsNil(o.UnitPrice) {
		return true
	}

	return false
}

// SetUnitPrice gets a reference to the given int32 and assigns it to the UnitPrice field.
func (o *InvoiceLineIn) SetUnitPrice(v int32) {
	o.UnitPrice = &v
}

func (o InvoiceLineIn) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InvoiceLineIn) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Amount) {
		toSerialize["amount"] = o.Amount
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Quantity) {
		toSerialize["quantity"] = o.Quantity
	}
	if !IsNil(o.UnitPrice) {
		toSerialize["unitPrice"] = o.UnitPrice
	}
	return toSerialize, nil
}

type NullableInvoiceLineIn struct {
	value *InvoiceLineIn
	isSet bool
}

func (v NullableInvoiceLineIn) Get() *InvoiceLineIn {
	return v.value
}

func (v *NullableInvoiceLineIn) Set(val *InvoiceLineIn) {
	v.value = val
	v.isSet = true
}

func (v NullableInvoiceLineIn) IsSet() bool {
	return v.isSet
}

func (v *NullableInvoiceLineIn) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInvoiceLineIn(val *InvoiceLineIn) *NullableInvoiceLineIn {
	return &NullableInvoiceLineIn{value: val, isSet: true}
}

func (v NullableInvoiceLineIn) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInvoiceLineIn) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
