/*
Hanzo Cloud API

Composed from each subsystem's own projection of its router, in the fleet's mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hanzoai

import (
	"encoding/json"
)

// checks if the O11yO11yMetricPoint type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &O11yO11yMetricPoint{}

// O11yO11yMetricPoint struct for O11yO11yMetricPoint
type O11yO11yMetricPoint struct {
	// Partial marks a point whose bucket the window only partly covers.
	Partial *bool `json:"partial,omitempty"`
	// Timestamp is the point's time as a Unix timestamp in milliseconds.
	Timestamp *int32 `json:"timestamp,omitempty"`
	// Value is the point's value.
	Value *float32 `json:"value,omitempty"`
	// Values carries the bucket values of a heatmap point.
	Values []float32 `json:"values,omitempty"`
}

// NewO11yO11yMetricPoint instantiates a new O11yO11yMetricPoint object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewO11yO11yMetricPoint() *O11yO11yMetricPoint {
	this := O11yO11yMetricPoint{}
	return &this
}

// NewO11yO11yMetricPointWithDefaults instantiates a new O11yO11yMetricPoint object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewO11yO11yMetricPointWithDefaults() *O11yO11yMetricPoint {
	this := O11yO11yMetricPoint{}
	return &this
}

// GetPartial returns the Partial field value if set, zero value otherwise.
func (o *O11yO11yMetricPoint) GetPartial() bool {
	if o == nil || IsNil(o.Partial) {
		var ret bool
		return ret
	}
	return *o.Partial
}

// GetPartialOk returns a tuple with the Partial field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *O11yO11yMetricPoint) GetPartialOk() (*bool, bool) {
	if o == nil || IsNil(o.Partial) {
		return nil, false
	}
	return o.Partial, true
}

// HasPartial returns a boolean if a field has been set.
func (o *O11yO11yMetricPoint) HasPartial() bool {
	if o != nil && !IsNil(o.Partial) {
		return true
	}

	return false
}

// SetPartial gets a reference to the given bool and assigns it to the Partial field.
func (o *O11yO11yMetricPoint) SetPartial(v bool) {
	o.Partial = &v
}

// GetTimestamp returns the Timestamp field value if set, zero value otherwise.
func (o *O11yO11yMetricPoint) GetTimestamp() int32 {
	if o == nil || IsNil(o.Timestamp) {
		var ret int32
		return ret
	}
	return *o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *O11yO11yMetricPoint) GetTimestampOk() (*int32, bool) {
	if o == nil || IsNil(o.Timestamp) {
		return nil, false
	}
	return o.Timestamp, true
}

// HasTimestamp returns a boolean if a field has been set.
func (o *O11yO11yMetricPoint) HasTimestamp() bool {
	if o != nil && !IsNil(o.Timestamp) {
		return true
	}

	return false
}

// SetTimestamp gets a reference to the given int32 and assigns it to the Timestamp field.
func (o *O11yO11yMetricPoint) SetTimestamp(v int32) {
	o.Timestamp = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *O11yO11yMetricPoint) GetValue() float32 {
	if o == nil || IsNil(o.Value) {
		var ret float32
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *O11yO11yMetricPoint) GetValueOk() (*float32, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *O11yO11yMetricPoint) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given float32 and assigns it to the Value field.
func (o *O11yO11yMetricPoint) SetValue(v float32) {
	o.Value = &v
}

// GetValues returns the Values field value if set, zero value otherwise.
func (o *O11yO11yMetricPoint) GetValues() []float32 {
	if o == nil || IsNil(o.Values) {
		var ret []float32
		return ret
	}
	return o.Values
}

// GetValuesOk returns a tuple with the Values field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *O11yO11yMetricPoint) GetValuesOk() ([]float32, bool) {
	if o == nil || IsNil(o.Values) {
		return nil, false
	}
	return o.Values, true
}

// HasValues returns a boolean if a field has been set.
func (o *O11yO11yMetricPoint) HasValues() bool {
	if o != nil && !IsNil(o.Values) {
		return true
	}

	return false
}

// SetValues gets a reference to the given []float32 and assigns it to the Values field.
func (o *O11yO11yMetricPoint) SetValues(v []float32) {
	o.Values = v
}

func (o O11yO11yMetricPoint) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o O11yO11yMetricPoint) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Partial) {
		toSerialize["partial"] = o.Partial
	}
	if !IsNil(o.Timestamp) {
		toSerialize["timestamp"] = o.Timestamp
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	if !IsNil(o.Values) {
		toSerialize["values"] = o.Values
	}
	return toSerialize, nil
}

type NullableO11yO11yMetricPoint struct {
	value *O11yO11yMetricPoint
	isSet bool
}

func (v NullableO11yO11yMetricPoint) Get() *O11yO11yMetricPoint {
	return v.value
}

func (v *NullableO11yO11yMetricPoint) Set(val *O11yO11yMetricPoint) {
	v.value = val
	v.isSet = true
}

func (v NullableO11yO11yMetricPoint) IsSet() bool {
	return v.isSet
}

func (v *NullableO11yO11yMetricPoint) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableO11yO11yMetricPoint(val *O11yO11yMetricPoint) *NullableO11yO11yMetricPoint {
	return &NullableO11yO11yMetricPoint{value: val, isSet: true}
}

func (v NullableO11yO11yMetricPoint) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableO11yO11yMetricPoint) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
