/*
Hanzo Cloud API

The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator's admin product, relay doors, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hanzoai

import (
	"encoding/json"
)

// checks if the O11yO11yPreferencesOut type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &O11yO11yPreferencesOut{}

// O11yO11yPreferencesOut struct for O11yO11yPreferencesOut
type O11yO11yPreferencesOut struct {
	// Data holds the preferences.
	Data []O11yO11yPreference `json:"data,omitempty"`
	// Status is \"success\".
	Status *string `json:"status,omitempty"`
}

// NewO11yO11yPreferencesOut instantiates a new O11yO11yPreferencesOut object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewO11yO11yPreferencesOut() *O11yO11yPreferencesOut {
	this := O11yO11yPreferencesOut{}
	return &this
}

// NewO11yO11yPreferencesOutWithDefaults instantiates a new O11yO11yPreferencesOut object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewO11yO11yPreferencesOutWithDefaults() *O11yO11yPreferencesOut {
	this := O11yO11yPreferencesOut{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *O11yO11yPreferencesOut) GetData() []O11yO11yPreference {
	if o == nil || IsNil(o.Data) {
		var ret []O11yO11yPreference
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *O11yO11yPreferencesOut) GetDataOk() ([]O11yO11yPreference, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *O11yO11yPreferencesOut) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []O11yO11yPreference and assigns it to the Data field.
func (o *O11yO11yPreferencesOut) SetData(v []O11yO11yPreference) {
	o.Data = v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *O11yO11yPreferencesOut) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *O11yO11yPreferencesOut) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *O11yO11yPreferencesOut) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *O11yO11yPreferencesOut) SetStatus(v string) {
	o.Status = &v
}

func (o O11yO11yPreferencesOut) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o O11yO11yPreferencesOut) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableO11yO11yPreferencesOut struct {
	value *O11yO11yPreferencesOut
	isSet bool
}

func (v NullableO11yO11yPreferencesOut) Get() *O11yO11yPreferencesOut {
	return v.value
}

func (v *NullableO11yO11yPreferencesOut) Set(val *O11yO11yPreferencesOut) {
	v.value = val
	v.isSet = true
}

func (v NullableO11yO11yPreferencesOut) IsSet() bool {
	return v.isSet
}

func (v *NullableO11yO11yPreferencesOut) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableO11yO11yPreferencesOut(val *O11yO11yPreferencesOut) *NullableO11yO11yPreferencesOut {
	return &NullableO11yO11yPreferencesOut{value: val, isSet: true}
}

func (v NullableO11yO11yPreferencesOut) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableO11yO11yPreferencesOut) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
