/*
Hanzo Cloud — Unified API (V8 · Open Edition)

The single unified OpenAPI surface for ALL Hanzo services, aggregated from the per-service specs. Every route is https://api.hanzo.ai/v1/<service>/_*. Grouped by the canonical domains in capabilities.yaml (the ONE registry). Regenerated by merge.py — edit the per-service <svc>/openapi.yaml + capabilities.yaml, not this file.

API version: 8.0.0
Contact: support@hanzo.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hanzoai

import (
	"encoding/json"
)

// checks if the AdminAdminMe200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdminAdminMe200Response{}

// AdminAdminMe200Response struct for AdminAdminMe200Response
type AdminAdminMe200Response struct {
	Status *string       `json:"status,omitempty"`
	Msg    *string       `json:"msg,omitempty"`
	Data   *AdminAdminMe `json:"data,omitempty"`
}

// NewAdminAdminMe200Response instantiates a new AdminAdminMe200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdminAdminMe200Response() *AdminAdminMe200Response {
	this := AdminAdminMe200Response{}
	return &this
}

// NewAdminAdminMe200ResponseWithDefaults instantiates a new AdminAdminMe200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdminAdminMe200ResponseWithDefaults() *AdminAdminMe200Response {
	this := AdminAdminMe200Response{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *AdminAdminMe200Response) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminAdminMe200Response) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *AdminAdminMe200Response) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *AdminAdminMe200Response) SetStatus(v string) {
	o.Status = &v
}

// GetMsg returns the Msg field value if set, zero value otherwise.
func (o *AdminAdminMe200Response) GetMsg() string {
	if o == nil || IsNil(o.Msg) {
		var ret string
		return ret
	}
	return *o.Msg
}

// GetMsgOk returns a tuple with the Msg field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminAdminMe200Response) GetMsgOk() (*string, bool) {
	if o == nil || IsNil(o.Msg) {
		return nil, false
	}
	return o.Msg, true
}

// HasMsg returns a boolean if a field has been set.
func (o *AdminAdminMe200Response) HasMsg() bool {
	if o != nil && !IsNil(o.Msg) {
		return true
	}

	return false
}

// SetMsg gets a reference to the given string and assigns it to the Msg field.
func (o *AdminAdminMe200Response) SetMsg(v string) {
	o.Msg = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *AdminAdminMe200Response) GetData() AdminAdminMe {
	if o == nil || IsNil(o.Data) {
		var ret AdminAdminMe
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminAdminMe200Response) GetDataOk() (*AdminAdminMe, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *AdminAdminMe200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given AdminAdminMe and assigns it to the Data field.
func (o *AdminAdminMe200Response) SetData(v AdminAdminMe) {
	o.Data = &v
}

func (o AdminAdminMe200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdminAdminMe200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Msg) {
		toSerialize["msg"] = o.Msg
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableAdminAdminMe200Response struct {
	value *AdminAdminMe200Response
	isSet bool
}

func (v NullableAdminAdminMe200Response) Get() *AdminAdminMe200Response {
	return v.value
}

func (v *NullableAdminAdminMe200Response) Set(val *AdminAdminMe200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableAdminAdminMe200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableAdminAdminMe200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdminAdminMe200Response(val *AdminAdminMe200Response) *NullableAdminAdminMe200Response {
	return &NullableAdminAdminMe200Response{value: val, isSet: true}
}

func (v NullableAdminAdminMe200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdminAdminMe200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
