/*
Hanzo Cloud API

Composed from each subsystem's own projection of its router, in the fleet's mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hanzoai

import (
	"encoding/json"
)

// checks if the ChannelMetric type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChannelMetric{}

// ChannelMetric struct for ChannelMetric
type ChannelMetric struct {
	// ExternalID is the provider-side id of the execution the spend belongs to. Absent until the channel has launched.
	ExternalId *string `json:"externalId,omitempty"`
	// Kind is which channel this row is: paid, organic or email. It is also the row's identity — a campaign carries at most one channel per kind.
	Kind *string `json:"kind,omitempty"`
	// Platform is the provider the spend was read from: meta, google, x, instagram, or the email provider.
	Platform *string `json:"platform,omitempty"`
	// SpendCents is what the provider itself reports this channel spent, in CENTS. 0 when the channel never launched, when no executor is wired for it, or when the read failed — SpendError tells the last case apart from a genuine zero.
	SpendCents *int32 `json:"spendCents,omitempty"`
	// SpendError is why this channel's spend could not be read (connector not connected, provider error), as one secret-free line. Present only on failure; the campaign total then simply omits this channel rather than failing.
	SpendError *string `json:"spendError,omitempty"`
	// Status is the channel's launch state on the campaign — pending, live, paused, failed or unavailable. Only a live channel is asked for its spend at all.
	Status *string `json:"status,omitempty"`
}

// NewChannelMetric instantiates a new ChannelMetric object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChannelMetric() *ChannelMetric {
	this := ChannelMetric{}
	return &this
}

// NewChannelMetricWithDefaults instantiates a new ChannelMetric object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChannelMetricWithDefaults() *ChannelMetric {
	this := ChannelMetric{}
	return &this
}

// GetExternalId returns the ExternalId field value if set, zero value otherwise.
func (o *ChannelMetric) GetExternalId() string {
	if o == nil || IsNil(o.ExternalId) {
		var ret string
		return ret
	}
	return *o.ExternalId
}

// GetExternalIdOk returns a tuple with the ExternalId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChannelMetric) GetExternalIdOk() (*string, bool) {
	if o == nil || IsNil(o.ExternalId) {
		return nil, false
	}
	return o.ExternalId, true
}

// HasExternalId returns a boolean if a field has been set.
func (o *ChannelMetric) HasExternalId() bool {
	if o != nil && !IsNil(o.ExternalId) {
		return true
	}

	return false
}

// SetExternalId gets a reference to the given string and assigns it to the ExternalId field.
func (o *ChannelMetric) SetExternalId(v string) {
	o.ExternalId = &v
}

// GetKind returns the Kind field value if set, zero value otherwise.
func (o *ChannelMetric) GetKind() string {
	if o == nil || IsNil(o.Kind) {
		var ret string
		return ret
	}
	return *o.Kind
}

// GetKindOk returns a tuple with the Kind field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChannelMetric) GetKindOk() (*string, bool) {
	if o == nil || IsNil(o.Kind) {
		return nil, false
	}
	return o.Kind, true
}

// HasKind returns a boolean if a field has been set.
func (o *ChannelMetric) HasKind() bool {
	if o != nil && !IsNil(o.Kind) {
		return true
	}

	return false
}

// SetKind gets a reference to the given string and assigns it to the Kind field.
func (o *ChannelMetric) SetKind(v string) {
	o.Kind = &v
}

// GetPlatform returns the Platform field value if set, zero value otherwise.
func (o *ChannelMetric) GetPlatform() string {
	if o == nil || IsNil(o.Platform) {
		var ret string
		return ret
	}
	return *o.Platform
}

// GetPlatformOk returns a tuple with the Platform field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChannelMetric) GetPlatformOk() (*string, bool) {
	if o == nil || IsNil(o.Platform) {
		return nil, false
	}
	return o.Platform, true
}

// HasPlatform returns a boolean if a field has been set.
func (o *ChannelMetric) HasPlatform() bool {
	if o != nil && !IsNil(o.Platform) {
		return true
	}

	return false
}

// SetPlatform gets a reference to the given string and assigns it to the Platform field.
func (o *ChannelMetric) SetPlatform(v string) {
	o.Platform = &v
}

// GetSpendCents returns the SpendCents field value if set, zero value otherwise.
func (o *ChannelMetric) GetSpendCents() int32 {
	if o == nil || IsNil(o.SpendCents) {
		var ret int32
		return ret
	}
	return *o.SpendCents
}

// GetSpendCentsOk returns a tuple with the SpendCents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChannelMetric) GetSpendCentsOk() (*int32, bool) {
	if o == nil || IsNil(o.SpendCents) {
		return nil, false
	}
	return o.SpendCents, true
}

// HasSpendCents returns a boolean if a field has been set.
func (o *ChannelMetric) HasSpendCents() bool {
	if o != nil && !IsNil(o.SpendCents) {
		return true
	}

	return false
}

// SetSpendCents gets a reference to the given int32 and assigns it to the SpendCents field.
func (o *ChannelMetric) SetSpendCents(v int32) {
	o.SpendCents = &v
}

// GetSpendError returns the SpendError field value if set, zero value otherwise.
func (o *ChannelMetric) GetSpendError() string {
	if o == nil || IsNil(o.SpendError) {
		var ret string
		return ret
	}
	return *o.SpendError
}

// GetSpendErrorOk returns a tuple with the SpendError field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChannelMetric) GetSpendErrorOk() (*string, bool) {
	if o == nil || IsNil(o.SpendError) {
		return nil, false
	}
	return o.SpendError, true
}

// HasSpendError returns a boolean if a field has been set.
func (o *ChannelMetric) HasSpendError() bool {
	if o != nil && !IsNil(o.SpendError) {
		return true
	}

	return false
}

// SetSpendError gets a reference to the given string and assigns it to the SpendError field.
func (o *ChannelMetric) SetSpendError(v string) {
	o.SpendError = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ChannelMetric) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChannelMetric) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ChannelMetric) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *ChannelMetric) SetStatus(v string) {
	o.Status = &v
}

func (o ChannelMetric) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChannelMetric) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ExternalId) {
		toSerialize["externalId"] = o.ExternalId
	}
	if !IsNil(o.Kind) {
		toSerialize["kind"] = o.Kind
	}
	if !IsNil(o.Platform) {
		toSerialize["platform"] = o.Platform
	}
	if !IsNil(o.SpendCents) {
		toSerialize["spendCents"] = o.SpendCents
	}
	if !IsNil(o.SpendError) {
		toSerialize["spendError"] = o.SpendError
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableChannelMetric struct {
	value *ChannelMetric
	isSet bool
}

func (v NullableChannelMetric) Get() *ChannelMetric {
	return v.value
}

func (v *NullableChannelMetric) Set(val *ChannelMetric) {
	v.value = val
	v.isSet = true
}

func (v NullableChannelMetric) IsSet() bool {
	return v.isSet
}

func (v *NullableChannelMetric) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChannelMetric(val *ChannelMetric) *NullableChannelMetric {
	return &NullableChannelMetric{value: val, isSet: true}
}

func (v NullableChannelMetric) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChannelMetric) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
