/*
Hanzo Cloud — Unified API (V8 · Open Edition)

The single unified OpenAPI surface for ALL Hanzo services, aggregated from the per-service specs. Every route is https://api.hanzo.ai/v1/<service>/_*. Grouped by the canonical domains in capabilities.yaml (the ONE registry). cloud/openapi.yaml is hanzoai/cloud's own woven document, copied verbatim by sync.py, and it wins wherever it and a hand-written spec describe the same route. Regenerated by merge.py — edit the per-service <svc>/openapi.yaml + capabilities.yaml, not this file.

API version: 8.0.0
Contact: support@hanzo.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hanzoai

import (
	"encoding/json"
)

// checks if the CloudCurateReq type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CloudCurateReq{}

// CloudCurateReq struct for CloudCurateReq
type CloudCurateReq struct {
	// Featured puts the listing on the front of the shelf, or takes it off.
	Featured *bool `json:"featured,omitempty"`
	// Hidden takes the listing off the org-visible shelf, or puts it back.
	Hidden *bool `json:"hidden,omitempty"`
	// ID is the listing to curate, from the path.
	Id *string `json:"id,omitempty"`
	// Logo is the brand mark to render, an https URL. Empty clears ours and lets the next sync adopt the publisher's own icon again.
	Logo *string `json:"logo,omitempty"`
	// Official overrides the derivation: setting it makes this answer FINAL, so no later sync re-derives over it. That is the difference between a default and a decision — the derivation can only tell that a domain-verified publisher serves the endpoint, not that the product is theirs.
	Official *bool `json:"official,omitempty"`
}

// NewCloudCurateReq instantiates a new CloudCurateReq object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCloudCurateReq() *CloudCurateReq {
	this := CloudCurateReq{}
	return &this
}

// NewCloudCurateReqWithDefaults instantiates a new CloudCurateReq object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCloudCurateReqWithDefaults() *CloudCurateReq {
	this := CloudCurateReq{}
	return &this
}

// GetFeatured returns the Featured field value if set, zero value otherwise.
func (o *CloudCurateReq) GetFeatured() bool {
	if o == nil || IsNil(o.Featured) {
		var ret bool
		return ret
	}
	return *o.Featured
}

// GetFeaturedOk returns a tuple with the Featured field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudCurateReq) GetFeaturedOk() (*bool, bool) {
	if o == nil || IsNil(o.Featured) {
		return nil, false
	}
	return o.Featured, true
}

// HasFeatured returns a boolean if a field has been set.
func (o *CloudCurateReq) HasFeatured() bool {
	if o != nil && !IsNil(o.Featured) {
		return true
	}

	return false
}

// SetFeatured gets a reference to the given bool and assigns it to the Featured field.
func (o *CloudCurateReq) SetFeatured(v bool) {
	o.Featured = &v
}

// GetHidden returns the Hidden field value if set, zero value otherwise.
func (o *CloudCurateReq) GetHidden() bool {
	if o == nil || IsNil(o.Hidden) {
		var ret bool
		return ret
	}
	return *o.Hidden
}

// GetHiddenOk returns a tuple with the Hidden field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudCurateReq) GetHiddenOk() (*bool, bool) {
	if o == nil || IsNil(o.Hidden) {
		return nil, false
	}
	return o.Hidden, true
}

// HasHidden returns a boolean if a field has been set.
func (o *CloudCurateReq) HasHidden() bool {
	if o != nil && !IsNil(o.Hidden) {
		return true
	}

	return false
}

// SetHidden gets a reference to the given bool and assigns it to the Hidden field.
func (o *CloudCurateReq) SetHidden(v bool) {
	o.Hidden = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *CloudCurateReq) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudCurateReq) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *CloudCurateReq) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *CloudCurateReq) SetId(v string) {
	o.Id = &v
}

// GetLogo returns the Logo field value if set, zero value otherwise.
func (o *CloudCurateReq) GetLogo() string {
	if o == nil || IsNil(o.Logo) {
		var ret string
		return ret
	}
	return *o.Logo
}

// GetLogoOk returns a tuple with the Logo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudCurateReq) GetLogoOk() (*string, bool) {
	if o == nil || IsNil(o.Logo) {
		return nil, false
	}
	return o.Logo, true
}

// HasLogo returns a boolean if a field has been set.
func (o *CloudCurateReq) HasLogo() bool {
	if o != nil && !IsNil(o.Logo) {
		return true
	}

	return false
}

// SetLogo gets a reference to the given string and assigns it to the Logo field.
func (o *CloudCurateReq) SetLogo(v string) {
	o.Logo = &v
}

// GetOfficial returns the Official field value if set, zero value otherwise.
func (o *CloudCurateReq) GetOfficial() bool {
	if o == nil || IsNil(o.Official) {
		var ret bool
		return ret
	}
	return *o.Official
}

// GetOfficialOk returns a tuple with the Official field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudCurateReq) GetOfficialOk() (*bool, bool) {
	if o == nil || IsNil(o.Official) {
		return nil, false
	}
	return o.Official, true
}

// HasOfficial returns a boolean if a field has been set.
func (o *CloudCurateReq) HasOfficial() bool {
	if o != nil && !IsNil(o.Official) {
		return true
	}

	return false
}

// SetOfficial gets a reference to the given bool and assigns it to the Official field.
func (o *CloudCurateReq) SetOfficial(v bool) {
	o.Official = &v
}

func (o CloudCurateReq) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CloudCurateReq) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Featured) {
		toSerialize["featured"] = o.Featured
	}
	if !IsNil(o.Hidden) {
		toSerialize["hidden"] = o.Hidden
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Logo) {
		toSerialize["logo"] = o.Logo
	}
	if !IsNil(o.Official) {
		toSerialize["official"] = o.Official
	}
	return toSerialize, nil
}

type NullableCloudCurateReq struct {
	value *CloudCurateReq
	isSet bool
}

func (v NullableCloudCurateReq) Get() *CloudCurateReq {
	return v.value
}

func (v *NullableCloudCurateReq) Set(val *CloudCurateReq) {
	v.value = val
	v.isSet = true
}

func (v NullableCloudCurateReq) IsSet() bool {
	return v.isSet
}

func (v *NullableCloudCurateReq) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCloudCurateReq(val *CloudCurateReq) *NullableCloudCurateReq {
	return &NullableCloudCurateReq{value: val, isSet: true}
}

func (v NullableCloudCurateReq) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCloudCurateReq) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
